export interface TutorialFuncionalidade {
  id: string;
  titulo: string;
  contexto: string;
  icone: string;
  rota: string;
  ordem: number;
}

export interface TutorialCategoria {
  id: string;
  nome: string;
  icone: string;
  cor: string;
  funcionalidades: TutorialFuncionalidade[];
}

export const TUTORIAL_CATEGORIES: TutorialCategoria[] = [
  {
    id: "pagina-inicial",
    nome: "Página Inicial",
    icone: "Home",
    cor: "from-blue-500 to-cyan-600",
    funcionalidades: [
      {
        id: "pesquisa-global",
        titulo: "Barra de Pesquisa",
        contexto: "Pesquisa inteligente que busca em todos os códigos, leis, artigos, flashcards e conteúdos do app. Aceita busca por número de lei, nome, tema ou palavras-chave.",
        icone: "Search",
        rota: "/",
        ordem: 1,
      },
      {
        id: "noticias-juridicas",
        titulo: "Notícias Jurídicas",
        contexto: "Carrossel com as principais notícias do mundo jurídico, atualizado diariamente. Inclui concursos, mudanças legislativas, decisões importantes dos tribunais.",
        icone: "Newspaper",
        rota: "/noticias",
        ordem: 2,
      },
      {
        id: "em-alta-vademecum",
        titulo: "Vade Mecum",
        contexto: "Acesso rápido a todos os códigos e leis brasileiros: Constituição Federal, Código Civil, Código Penal, CPC, CPP, CLT, CTB, Estatutos, Súmulas e muito mais.",
        icone: "BookOpen",
        rota: "/vade-mecum",
        ordem: 3,
      },
      {
        id: "em-alta-questoes",
        titulo: "Questões de Provas",
        contexto: "Banco de questões por área do direito e por artigo de lei. Pratique com questões de concursos e OAB, com explicações detalhadas e gabarito comentado.",
        icone: "HelpCircle",
        rota: "/questoes",
        ordem: 4,
      },
      {
        id: "em-alta-cursos",
        titulo: "Cursos",
        contexto: "Cursos completos de diversas áreas do direito, do básico ao avançado. Inclui videoaulas, materiais complementares e certificados.",
        icone: "GraduationCap",
        rota: "/cursos",
        ordem: 5,
      },
      {
        id: "em-alta-blog",
        titulo: "Blog Jurídico",
        contexto: "Artigos sobre carreiras jurídicas (advogado, juiz, delegado, promotor), curiosidades do direito, história do direito, filósofos e termos jurídicos.",
        icone: "FileText",
        rota: "/blog-juridico",
        ordem: 6,
      },
      {
        id: "estudos-flashcards",
        titulo: "Flashcards",
        contexto: "Flashcards inteligentes para memorização de artigos de lei. Modos: por artigo, por área do direito, complete a lei. Sistema de repetição espaçada.",
        icone: "Brain",
        rota: "/flashcards",
        ordem: 7,
      },
      {
        id: "estudos-resumos",
        titulo: "Resumos Jurídicos",
        contexto: "Resumos organizados por área > tema > subtema. Conteúdo gerado por IA com base nos códigos e doutrinas. Ideal para revisão rápida antes de provas.",
        icone: "FileText",
        rota: "/resumos",
        ordem: 8,
      },
      {
        id: "estudos-biblioteca",
        titulo: "Bibliotecas",
        contexto: "Bibliotecas digitais com livros de estudos, clássicos do direito, liderança, oratória. Leitura dinâmica com formatação otimizada para celular.",
        icone: "Library",
        rota: "/biblioteca-digital",
        ordem: 9,
      },
      {
        id: "estudos-mapa-mental",
        titulo: "Mapa Mental",
        contexto: "Mapas mentais interativos organizados por área do direito. Visualize conexões entre conceitos e navegue pelos temas de forma visual.",
        icone: "GitBranch",
        rota: "/mapa-mental",
        ordem: 10,
      },
      {
        id: "estudos-plano",
        titulo: "Plano de Estudos",
        contexto: "Crie seu plano de estudos personalizado. Defina metas, acompanhe seu progresso e receba sugestões de conteúdo baseadas no seu objetivo.",
        icone: "Calendar",
        rota: "/plano-estudos",
        ordem: 11,
      },
      {
        id: "estudos-videoaulas",
        titulo: "Videoaulas",
        contexto: "Videoaulas de professores especializados em diversas áreas do direito. Conteúdo em vídeo para complementar seus estudos.",
        icone: "PlayCircle",
        rota: "/videoaulas",
        ordem: 12,
      },
      {
        id: "oab-estudar",
        titulo: "OAB - O que Estudar",
        contexto: "Guia completo do que estudar para a OAB. Conteúdo organizado por disciplina, com peso de cada matéria e dicas de estudo estratégico.",
        icone: "BookMarked",
        rota: "/oab",
        ordem: 13,
      },
      {
        id: "oab-biblioteca",
        titulo: "Biblioteca OAB",
        contexto: "Biblioteca específica para a OAB com materiais focados no exame. Inclui súmulas vinculantes, informativos e jurisprudência mais cobrada.",
        icone: "Library",
        rota: "/biblioteca-oab",
        ordem: 14,
      },
      {
        id: "oab-questoes",
        titulo: "Questões OAB",
        contexto: "Questões de provas anteriores da OAB organizadas por disciplina e exame. Estatísticas de aproveitamento e simulados cronometrados.",
        icone: "HelpCircle",
        rota: "/questoes-oab",
        ordem: 15,
      },
    ],
  },
  {
    id: "vade-mecum",
    nome: "Vade Mecum",
    icone: "Scale",
    cor: "from-purple-500 to-violet-600",
    funcionalidades: [
      {
        id: "vm-busca",
        titulo: "Busca de Leis",
        contexto: "Busca inteligente por número de lei (ex: 13869), nome (ex: LGPD), artigo ou palavra-chave. Busca em todos os códigos, estatutos e leis simultaneamente.",
        icone: "Search",
        rota: "/vade-mecum",
        ordem: 1,
      },
      {
        id: "vm-constituicao",
        titulo: "Constituição Federal",
        contexto: "Constituição Federal de 1988 completa com todos os artigos. Inclui explicações, exemplos práticos, termos jurídicos e narração em áudio.",
        icone: "BookOpen",
        rota: "/constituicao-federal",
        ordem: 2,
      },
      {
        id: "vm-codigos",
        titulo: "Códigos Principais",
        contexto: "Código Civil, Código Penal, CPC, CPP, CLT, CTB, CDC e outros 30+ códigos. Cada artigo com explicação simplificada e técnica, exemplos e questões.",
        icone: "Gavel",
        rota: "/vade-mecum",
        ordem: 3,
      },
      {
        id: "vm-estatutos",
        titulo: "Estatutos",
        contexto: "ECA, Estatuto do Idoso, da Criança, do Desarmamento, da Cidade e outros. Legislação especial com foco em grupos específicos e situações.",
        icone: "Users",
        rota: "/vade-mecum",
        ordem: 4,
      },
      {
        id: "vm-leis-penais",
        titulo: "Legislação Penal Especial",
        contexto: "Leis penais especiais: crimes hediondos, drogas, armas, violência doméstica, crimes contra idoso, lavagem de dinheiro e mais.",
        icone: "AlertTriangle",
        rota: "/vade-mecum",
        ordem: 5,
      },
      {
        id: "vm-sumulas",
        titulo: "Súmulas",
        contexto: "Súmulas do STF, STJ, TST e outros tribunais. Enunciados que consolidam a jurisprudência dominante sobre temas específicos.",
        icone: "FileCheck",
        rota: "/sumulas",
        ordem: 6,
      },
      {
        id: "vm-leis-ordinarias",
        titulo: "Leis Ordinárias",
        contexto: "LGPD, Marco Civil da Internet, Lei de Licitações, Lei de Improbidade e outras leis ordinárias importantes para concursos e OAB.",
        icone: "ScrollText",
        rota: "/vade-mecum",
        ordem: 7,
      },
    ],
  },
  {
    id: "dentro-artigo",
    nome: "Leitura de Artigos",
    icone: "FileText",
    cor: "from-emerald-500 to-teal-600",
    funcionalidades: [
      {
        id: "art-lista",
        titulo: "Lista de Artigos",
        contexto: "Lista completa de todos os artigos da lei selecionada. Ordenados por número, com busca rápida e contador de total de artigos.",
        icone: "List",
        rota: "/",
        ordem: 1,
      },
      {
        id: "art-busca",
        titulo: "Busca por Artigo",
        contexto: "Digite o número do artigo ou palavra-chave para encontrar rapidamente. Busca em tempo real conforme você digita.",
        icone: "Search",
        rota: "/",
        ordem: 2,
      },
      {
        id: "art-narracao",
        titulo: "Narração em Áudio",
        contexto: "Ouça o artigo narrado. Ideal para estudar enquanto faz outras atividades. Gerado automaticamente por IA com voz natural.",
        icone: "Volume2",
        rota: "/",
        ordem: 3,
      },
      {
        id: "art-texto",
        titulo: "Texto do Artigo",
        contexto: "Texto original da lei conforme publicado oficialmente. Base para todas as explicações e estudos.",
        icone: "FileText",
        rota: "/",
        ordem: 4,
      },
      {
        id: "art-explicacao",
        titulo: "Explicação Simplificada",
        contexto: "Explicação em linguagem simples do que o artigo significa na prática. Duas versões: técnica (para profissionais) e simplificada (para iniciantes).",
        icone: "MessageSquare",
        rota: "/",
        ordem: 5,
      },
      {
        id: "art-exemplo",
        titulo: "Exemplo Prático",
        contexto: "Situação real de aplicação do artigo. Casos do dia a dia que ilustram quando e como a lei se aplica.",
        icone: "Lightbulb",
        rota: "/",
        ordem: 6,
      },
      {
        id: "art-termos",
        titulo: "Termos Jurídicos",
        contexto: "Lista de termos técnicos presentes no artigo com suas definições. Clique em qualquer termo para ver o significado.",
        icone: "BookOpen",
        rota: "/",
        ordem: 7,
      },
      {
        id: "art-fonte",
        titulo: "Ajuste de Fonte",
        contexto: "Aumente ou diminua o tamanho da fonte para leitura confortável. Botões A+ e A- para ajuste rápido.",
        icone: "Type",
        rota: "/",
        ordem: 8,
      },
      {
        id: "art-compartilhar",
        titulo: "Compartilhar",
        contexto: "Compartilhe o artigo via WhatsApp, copie para a área de transferência ou gere imagem para redes sociais.",
        icone: "Share2",
        rota: "/",
        ordem: 9,
      },
    ],
  },
  {
    id: "ferramentas-estudo",
    nome: "Ferramentas de Estudo",
    icone: "Wrench",
    cor: "from-amber-500 to-orange-600",
    funcionalidades: [
      {
        id: "tool-flashcards",
        titulo: "Flashcards Inteligentes",
        contexto: "Três modos de estudo: Por Artigo (flashcards de artigos específicos), Por Área (temas como Direito Penal, Civil), Complete a Lei (preencha lacunas). Sistema de repetição espaçada.",
        icone: "Brain",
        rota: "/flashcards",
        ordem: 1,
      },
      {
        id: "tool-resumos",
        titulo: "Resumos por Área",
        contexto: "Resumos organizados em hierarquia: Área > Tema > Subtema. Ex: Direito Civil > Contratos > Compra e Venda. Gerado por IA com base na legislação.",
        icone: "FileText",
        rota: "/resumos",
        ordem: 2,
      },
      {
        id: "tool-questoes",
        titulo: "Questões de Provas",
        contexto: "Questões de concursos e OAB organizadas por área ou por artigo. Gabarito comentado, estatísticas de aproveitamento, modo simulado.",
        icone: "HelpCircle",
        rota: "/questoes",
        ordem: 3,
      },
      {
        id: "tool-mapa",
        titulo: "Mapa Mental",
        contexto: "Visualize conexões entre conceitos jurídicos. Navegue pelos temas de forma visual e interativa. Expanda nós para ver detalhes.",
        icone: "GitBranch",
        rota: "/mapa-mental",
        ordem: 4,
      },
      {
        id: "tool-plano",
        titulo: "Plano de Estudos",
        contexto: "Monte seu cronograma de estudos personalizado. Defina objetivo (OAB, concurso específico), prazo e disponibilidade. Acompanhe progresso.",
        icone: "Calendar",
        rota: "/plano-estudos",
        ordem: 5,
      },
      {
        id: "tool-audioaulas",
        titulo: "Audioaulas",
        contexto: "Aulas em áudio por tema. Três categorias: Estudos (teoria), Artigos (flashcards narrados), Resumos (revisão rápida). Ouça no carro ou academia.",
        icone: "Headphones",
        rota: "/audioaulas",
        ordem: 6,
      },
    ],
  },
  {
    id: "outras-ferramentas",
    nome: "Mais Recursos",
    icone: "Sparkles",
    cor: "from-pink-500 to-rose-600",
    funcionalidades: [
      {
        id: "other-professora",
        titulo: "Assistente IA (Professora)",
        contexto: "Chat com inteligência artificial especializada em direito. Tire dúvidas, peça explicações, gere questões, simule casos práticos. Múltiplos modos de conversa.",
        icone: "MessageCircle",
        rota: "/chat-professora",
        ordem: 1,
      },
      {
        id: "other-noticias",
        titulo: "Notícias Jurídicas",
        contexto: "Notícias atualizadas do mundo jurídico. Mudanças legislativas, decisões importantes, concursos abertos. Resumo executivo por IA.",
        icone: "Newspaper",
        rota: "/noticias",
        ordem: 2,
      },
      {
        id: "other-peticoes",
        titulo: "Modelos de Petições",
        contexto: "Modelos de petições para diversas situações. Petição inicial, contestação, recursos. Personalize com seus dados e caso específico.",
        icone: "FileEdit",
        rota: "/peticoes",
        ordem: 3,
      },
      {
        id: "other-juriflix",
        titulo: "JuriFlix",
        contexto: "Filmes, séries e documentários com temas jurídicos recomendados. Descubra produções que abordam o direito de forma interessante.",
        icone: "Film",
        rota: "/juriflix",
        ordem: 4,
      },
      {
        id: "other-dicionario",
        titulo: "Dicionário Jurídico",
        contexto: "Dicionário completo de termos jurídicos. Busque por termo ou navegue por letra. Definições claras com exemplos de uso.",
        icone: "Book",
        rota: "/dicionario",
        ordem: 5,
      },
      {
        id: "other-politica",
        titulo: "Política - Estou Te Vendo",
        contexto: "Acompanhe a política brasileira. Rankings de deputados (gastos, propostas, presença), notícias políticas, blog sobre instituições e história política.",
        icone: "Eye",
        rota: "/politica",
        ordem: 6,
      },
    ],
  },
  {
    id: "navegacao",
    nome: "Navegação",
    icone: "Navigation",
    cor: "from-slate-500 to-gray-600",
    funcionalidades: [
      {
        id: "nav-inicio",
        titulo: "Botão Início",
        contexto: "Volta para a página inicial do app. Acesso rápido a todas as funções principais e destaques.",
        icone: "Home",
        rota: "/",
        ordem: 1,
      },
      {
        id: "nav-ferramentas",
        titulo: "Botão Ferramentas",
        contexto: "Acesso ao hub de ferramentas: flashcards, resumos, questões, mapa mental, plano de estudos e mais.",
        icone: "Wrench",
        rota: "/ferramentas",
        ordem: 2,
      },
      {
        id: "nav-professora",
        titulo: "Botão Professora",
        contexto: "Atalho central para o chat com a assistente IA. Tire dúvidas rapidamente a qualquer momento.",
        icone: "MessageCircle",
        rota: "/chat-professora",
        ordem: 3,
      },
      {
        id: "nav-desktop",
        titulo: "Botão Desktop",
        contexto: "Acesse o app pelo computador. Gera QR Code ou link para abrir no navegador do PC com tela maior.",
        icone: "Monitor",
        rota: "/acesso-desktop",
        ordem: 4,
      },
      {
        id: "nav-menu",
        titulo: "Menu Lateral",
        contexto: "Menu completo com todas as funções do app. Novidades, configurações, bibliotecas especiais e mais opções.",
        icone: "Menu",
        rota: "/",
        ordem: 5,
      },
    ],
  },
];

export const getCategoryById = (id: string): TutorialCategoria | undefined => {
  return TUTORIAL_CATEGORIES.find((cat) => cat.id === id);
};

export const getAllFuncionalidades = (): TutorialFuncionalidade[] => {
  return TUTORIAL_CATEGORIES.flatMap((cat) => cat.funcionalidades);
};
