-- Adicionar colunas de resumo na tabela BIBLIOTECA-CLASSICOS
ALTER TABLE "BIBLIOTECA-CLASSICOS" ADD COLUMN IF NOT EXISTS resumo_capitulos jsonb;
ALTER TABLE "BIBLIOTECA-CLASSICOS" ADD COLUMN IF NOT EXISTS questoes_resumo jsonb;
ALTER TABLE "BIBLIOTECA-CLASSICOS" ADD COLUMN IF NOT EXISTS resumo_gerado_em timestamptz;

-- Adicionar colunas de resumo na tabela BIBLIOTECA-ORATORIA
ALTER TABLE "BIBLIOTECA-ORATORIA" ADD COLUMN IF NOT EXISTS resumo_capitulos jsonb;
ALTER TABLE "BIBLIOTECA-ORATORIA" ADD COLUMN IF NOT EXISTS questoes_resumo jsonb;
ALTER TABLE "BIBLIOTECA-ORATORIA" ADD COLUMN IF NOT EXISTS resumo_gerado_em timestamptz;

-- Adicionar colunas de resumo na tabela BIBLIOTECA-LIDERANÇA
ALTER TABLE "BIBLIOTECA-LIDERANÇA" ADD COLUMN IF NOT EXISTS resumo_capitulos jsonb;
ALTER TABLE "BIBLIOTECA-LIDERANÇA" ADD COLUMN IF NOT EXISTS questoes_resumo jsonb;
ALTER TABLE "BIBLIOTECA-LIDERANÇA" ADD COLUMN IF NOT EXISTS resumo_gerado_em timestamptz;