-- Anhanguera (universidade_id=3) - Topics for all disciplines
-- Semester 1
INSERT INTO faculdade_topicos (disciplina_id, titulo, ordem) VALUES
(140, 'Sociedade da Informação e do Conhecimento', 1),
(140, 'Transformação Digital e Impactos Sociais', 2),
(140, 'Inclusão Digital e Cidadania', 3),
(140, 'Ferramentas Digitais para o Direito', 4),
(140, 'Ética e Segurança no Ambiente Digital', 5),
(140, 'Propriedade Intelectual no Meio Digital', 6),
(141, 'Conceito e Natureza do Direito', 1),
(141, 'Fontes do Direito', 2),
(141, 'História do Direito no Brasil', 3),
(141, 'Norma Jurídica: Estrutura e Classificação', 4),
(141, 'Relação Jurídica e Sujeitos de Direito', 5),
(141, 'Direito Objetivo e Direito Subjetivo', 6),
(141, 'Ramos do Direito', 7),
(141, 'Hermenêutica Jurídica e Interpretação', 8),
(141, 'Lacunas e Antinomias do Direito', 9),
(141, 'Eficácia e Vigência das Normas', 10),
(142, 'Introdução à Psicologia Jurídica', 1),
(142, 'Processos Psicológicos Básicos', 2),
(142, 'Personalidade e Comportamento', 3),
(142, 'Psicologia do Testemunho', 4),
(142, 'Psicologia Forense e Criminal', 5),
(142, 'Mediação e Resolução de Conflitos', 6),
(142, 'Psicologia da Família e Infância', 7),
(142, 'Laudos e Perícias Psicológicas', 8),
(143, 'Lógica Formal e Lógica Jurídica', 1),
(143, 'Teoria da Argumentação', 2),
(143, 'Retórica e Persuasão no Direito', 3),
(143, 'Tipos de Argumentos Jurídicos', 4),
(143, 'Falácias Argumentativas', 5),
(143, 'Fundamentação de Decisões Judiciais', 6),
(143, 'Técnicas de Redação Jurídica', 7),
(144, 'Constitucionalismo: Origem e Evolução', 1),
(144, 'Poder Constituinte', 2),
(144, 'Classificação das Constituições', 3),
(144, 'Princípios Fundamentais da CF/88', 4),
(144, 'Direitos e Garantias Fundamentais', 5),
(144, 'Nacionalidade e Direitos Políticos', 6),
(144, 'Organização do Estado', 7),
(144, 'Separação dos Poderes', 8),
(144, 'Controle de Constitucionalidade', 9),
(144, 'Remédios Constitucionais', 10),
(145, 'Pessoa Natural: Personalidade e Capacidade', 1),
(145, 'Direitos da Personalidade', 2),
(145, 'Pessoa Jurídica', 3),
(145, 'Domicílio', 4),
(145, 'Bens Jurídicos: Classificação', 5),
(145, 'Fatos Jurídicos', 6),
(145, 'Negócio Jurídico: Elementos e Requisitos', 7),
(145, 'Defeitos do Negócio Jurídico', 8),
(145, 'Invalidade do Negócio Jurídico', 9),
(145, 'Prescrição e Decadência', 10),
(146, 'Princípios do Direito do Trabalho', 1),
(146, 'Relação de Emprego e Relação de Trabalho', 2),
(146, 'Contrato Individual de Trabalho', 3),
(146, 'Jornada de Trabalho', 4),
(146, 'Remuneração e Salário', 5),
(146, 'Férias e 13º Salário', 6),
(146, 'FGTS e Seguro-Desemprego', 7),
(146, 'Rescisão do Contrato de Trabalho', 8),
(146, 'Aviso Prévio e Verbas Rescisórias', 9),
(146, 'Trabalho da Mulher, do Menor e Doméstico', 10),
(147, 'Jurisdição: Conceito e Princípios', 1),
(147, 'Ação: Teorias e Condições', 2),
(147, 'Processo: Natureza Jurídica', 3),
(147, 'Competência', 4),
(147, 'Sujeitos do Processo', 5),
(147, 'Atos Processuais', 6),
(147, 'Pressupostos Processuais', 7),
(147, 'Tutela Provisória', 8),
(147, 'Princípios Processuais Constitucionais', 9),
(148, 'Princípios do Direito Penal', 1),
(148, 'Aplicação da Lei Penal no Tempo e Espaço', 2),
(148, 'Teoria do Crime: Conceito Analítico', 3),
(148, 'Tipicidade e Ilicitude', 4),
(148, 'Culpabilidade', 5),
(148, 'Iter Criminis e Tentativa', 6),
(148, 'Concurso de Pessoas', 7),
(148, 'Concurso de Crimes', 8),
(148, 'Causas de Exclusão de Ilicitude', 9),
(148, 'Imputabilidade Penal', 10),
(149, 'Conceito e Elementos das Obrigações', 1),
(149, 'Classificação das Obrigações', 2),
(149, 'Transmissão das Obrigações', 3),
(149, 'Adimplemento e Extinção das Obrigações', 4),
(149, 'Inadimplemento das Obrigações', 5),
(149, 'Mora e Perdas e Danos', 6),
(149, 'Cláusula Penal e Arras', 7),
(149, 'Responsabilidade Civil Contratual', 8),
(150, 'Organização dos Poderes: Legislativo', 1),
(150, 'Processo Legislativo', 2),
(150, 'Organização dos Poderes: Executivo', 3),
(150, 'Organização dos Poderes: Judiciário', 4),
(150, 'Funções Essenciais à Justiça', 5),
(150, 'Ordem Econômica e Financeira', 6),
(150, 'Ordem Social', 7),
(150, 'Tributação e Orçamento', 8),
(150, 'Estado de Defesa e Estado de Sítio', 9),
(151, 'Teoria das Penas: Fundamentos', 1),
(151, 'Penas Privativas de Liberdade', 2),
(151, 'Penas Restritivas de Direitos', 3),
(151, 'Pena de Multa', 4),
(151, 'Aplicação da Pena: Dosimetria', 5),
(151, 'Suspensão Condicional da Pena', 6),
(151, 'Livramento Condicional', 7),
(151, 'Efeitos da Condenação e Reabilitação', 8),
(151, 'Lei de Execução Penal (LEP)', 9),
(151, 'Regime Prisional e Progressão', 10),
(152, 'Petição Inicial: Requisitos e Vícios', 1),
(152, 'Citação e Intimação', 2),
(152, 'Contestação e Reconvenção', 3),
(152, 'Julgamento Antecipado e Saneamento', 4),
(152, 'Provas no Processo Civil', 5),
(152, 'Audiência de Instrução e Julgamento', 6),
(152, 'Sentença: Conceito e Classificação', 7),
(152, 'Coisa Julgada', 8),
(152, 'Tutela de Urgência e Evidência', 9),
(153, 'Princípios do Direito Ambiental', 1),
(153, 'Competência Ambiental', 2),
(153, 'Política Nacional do Meio Ambiente', 3),
(153, 'Licenciamento Ambiental', 4),
(153, 'Estudo de Impacto Ambiental (EIA/RIMA)', 5),
(153, 'Responsabilidade Civil Ambiental', 6),
(153, 'Crimes Ambientais (Lei 9.605/98)', 7),
(153, 'Áreas de Proteção e Unidades de Conservação', 8),
(153, 'Recursos Hídricos', 9),
(154, 'Teoria Geral dos Contratos', 1),
(154, 'Formação dos Contratos', 2),
(154, 'Classificação dos Contratos', 3),
(154, 'Extinção dos Contratos', 4),
(154, 'Compra e Venda', 5),
(154, 'Doação', 6),
(154, 'Locação de Coisas', 7),
(154, 'Prestação de Serviço e Empreitada', 8),
(154, 'Mandato, Fiança e Seguro', 9),
(154, 'Contratos Bancários e Eletrônicos', 10),
(155, 'Princípios do Direito Coletivo do Trabalho', 1),
(155, 'Sindicatos: Organização e Estrutura', 2),
(155, 'Negociação Coletiva', 3),
(155, 'Convenção e Acordo Coletivo', 4),
(155, 'Greve e Lockout', 5),
(155, 'Dissídio Coletivo', 6),
(155, 'Ações Coletivas: Ação Civil Pública', 7),
(155, 'Mandado de Segurança Coletivo', 8),
(156, 'Ordem Econômica na Constituição', 1),
(156, 'Princípios da Atividade Econômica', 2),
(156, 'Direito da Concorrência (CADE)', 3),
(156, 'Regulação Econômica e Agências Reguladoras', 4),
(156, 'Direito Financeiro: Orçamento Público', 5),
(156, 'Lei de Responsabilidade Fiscal', 6),
(156, 'Crédito Público e Dívida Pública', 7),
(156, 'Sistema Financeiro Nacional', 8),
(157, 'Crimes contra a Pessoa', 1),
(157, 'Crimes contra o Patrimônio', 2),
(157, 'Crimes contra a Dignidade Sexual', 3),
(157, 'Crimes contra a Família', 4),
(157, 'Crimes contra a Incolumidade Pública', 5),
(157, 'Crimes contra a Fé Pública', 6),
(157, 'Crimes contra a Administração Pública', 7),
(157, 'Legislação Penal Especial', 8),
(158, 'Teoria Geral da Execução', 1),
(158, 'Título Executivo Judicial e Extrajudicial', 2),
(158, 'Cumprimento de Sentença', 3),
(158, 'Execução por Quantia Certa', 4),
(158, 'Penhora e Avaliação', 5),
(158, 'Execução de Obrigação de Fazer e Não Fazer', 6),
(158, 'Embargos à Execução', 7),
(158, 'Execução Fiscal (LEF)', 8),
(158, 'Execução contra a Fazenda Pública', 9),
(159, 'Princípios do Processo do Trabalho', 1),
(159, 'Organização da Justiça do Trabalho', 2),
(159, 'Competência da Justiça do Trabalho', 3),
(159, 'Reclamação Trabalhista', 4),
(159, 'Audiência Trabalhista', 5),
(159, 'Provas no Processo do Trabalho', 6),
(159, 'Recursos Trabalhistas', 7),
(159, 'Execução Trabalhista', 8),
(160, 'Jusnaturalismo e Juspositivismo', 1),
(160, 'Teoria da Justiça', 2),
(160, 'Sociologia Jurídica: Conceitos Básicos', 3),
(160, 'Direito e Sociedade', 4),
(160, 'Pluralismo Jurídico', 5),
(160, 'Direito e Poder', 6),
(160, 'Eficácia Social do Direito', 7),
(161, 'Princípios da Administração Pública', 1),
(161, 'Organização Administrativa', 2),
(161, 'Atos Administrativos', 3),
(161, 'Poderes da Administração', 4),
(161, 'Licitações e Contratos (Lei 14.133/21)', 5),
(161, 'Servidores Públicos', 6),
(161, 'Serviços Públicos', 7),
(161, 'Responsabilidade Civil do Estado', 8),
(161, 'Bens Públicos', 9),
(161, 'Controle da Administração', 10),
(162, 'Posse: Conceito e Classificação', 1),
(162, 'Efeitos da Posse', 2),
(162, 'Propriedade: Aquisição e Perda', 3),
(162, 'Função Social da Propriedade', 4),
(162, 'Direitos Reais sobre Coisa Alheia', 5),
(162, 'Usufruto e Servidões', 6),
(162, 'Hipoteca, Penhor e Anticrese', 7),
(162, 'Condomínio', 8),
(162, 'Direitos Reais de Garantia', 9),
(163, 'Teoria da Empresa', 1),
(163, 'Empresário Individual e EIRELI', 2),
(163, 'Registro de Empresas', 3),
(163, 'Estabelecimento Empresarial', 4),
(163, 'Sociedades: Conceito e Classificação', 5),
(163, 'Sociedade Limitada', 6),
(163, 'Sociedade Anônima', 7),
(163, 'Propriedade Industrial', 8),
(164, 'Seguridade Social: Conceito e Princípios', 1),
(164, 'Regime Geral de Previdência Social (RGPS)', 2),
(164, 'Segurados e Dependentes', 3),
(164, 'Salário de Contribuição', 4),
(164, 'Benefícios Previdenciários', 5),
(164, 'Aposentadoria: Modalidades', 6),
(164, 'Auxílio-Doença e Auxílio-Acidente', 7),
(164, 'Pensão por Morte e Salário-Maternidade', 8),
(164, 'Custeio da Previdência Social', 9),
(165, 'Responsabilidade Civil: Elementos', 1),
(165, 'Responsabilidade Objetiva e Subjetiva', 2),
(165, 'Dano Material, Moral e Estético', 3),
(165, 'Excludentes de Responsabilidade', 4),
(165, 'Código de Defesa do Consumidor: Princípios', 5),
(165, 'Relação de Consumo', 6),
(165, 'Responsabilidade pelo Fato e Vício do Produto', 7),
(165, 'Práticas Comerciais Abusivas', 8),
(165, 'Proteção Contratual do Consumidor', 9),
(166, 'Casamento: Requisitos e Impedimentos', 1),
(166, 'Regime de Bens', 2),
(166, 'Dissolução do Casamento', 3),
(166, 'União Estável', 4),
(166, 'Relações de Parentesco', 5),
(166, 'Filiação e Reconhecimento', 6),
(166, 'Poder Familiar', 7),
(166, 'Guarda e Visitação', 8),
(166, 'Alimentos', 9),
(166, 'Tutela e Curatela', 10),
(167, 'Teoria Geral dos Recursos', 1),
(167, 'Apelação', 2),
(167, 'Agravo de Instrumento', 3),
(167, 'Embargos de Declaração', 4),
(167, 'Recurso Especial e Recurso Extraordinário', 5),
(167, 'Recurso Ordinário', 6),
(167, 'Embargos de Divergência', 7),
(167, 'Ação Rescisória', 8),
(167, 'Reclamação', 9),
(168, 'Estatuto da OAB', 1),
(168, 'Código de Ética e Disciplina da OAB', 2),
(168, 'Direitos e Deveres do Advogado', 3),
(168, 'Incompatibilidades e Impedimentos', 4),
(168, 'Honorários Advocatícios', 5),
(168, 'Sigilo Profissional', 6),
(168, 'Publicidade na Advocacia', 7),
(168, 'Infrações e Sanções Disciplinares', 8),
(169, 'Petição Inicial: Elaboração Prática', 1),
(169, 'Contestação e Exceções', 2),
(169, 'Audiências Simuladas', 3),
(169, 'Recursos na Prática', 4),
(169, 'Prática em Juizados Especiais', 5),
(169, 'Atendimento ao Cliente', 6),
(170, 'Mediação: Conceito e Técnicas', 1),
(170, 'Conciliação Judicial e Extrajudicial', 2),
(170, 'Arbitragem (Lei 9.307/96)', 3),
(170, 'Negociação e Justiça Restaurativa', 4),
(170, 'Câmaras de Mediação e Arbitragem', 5),
(170, 'Papel do Mediador e do Árbitro', 6),
(171, 'Abertura da Sucessão', 1),
(171, 'Sucessão Legítima', 2),
(171, 'Ordem de Vocação Hereditária', 3),
(171, 'Sucessão Testamentária', 4),
(171, 'Formas de Testamento', 5),
(171, 'Legados e Substituições', 6),
(171, 'Inventário e Partilha', 7),
(171, 'Herança Jacente e Vacante', 8),
(172, 'Inquérito Policial', 1),
(172, 'Ação Penal: Pública e Privada', 2),
(172, 'Competência no Processo Penal', 3),
(172, 'Provas no Processo Penal', 4),
(172, 'Prisão e Liberdade Provisória', 5),
(172, 'Citação e Intimação no Processo Penal', 6),
(172, 'Procedimento Comum e Especial', 7),
(172, 'Recursos no Processo Penal', 8),
(172, 'Habeas Corpus', 9),
(172, 'Tribunal do Júri', 10),
(173, 'Prática em Direito Penal', 1),
(173, 'Prática em Direito do Trabalho', 2),
(173, 'Elaboração de Peças Processuais', 3),
(173, 'Audiências e Sustentação Oral', 4),
(173, 'Atendimento no NPJ', 5),
(174, 'Teoria Geral dos Títulos de Crédito', 1),
(174, 'Letra de Câmbio e Nota Promissória', 2),
(174, 'Cheque e Duplicata', 3),
(174, 'Endosso, Aval e Protesto', 4),
(174, 'Recuperação Judicial', 5),
(174, 'Recuperação Extrajudicial', 6),
(174, 'Falência: Processo e Efeitos', 7),
(174, 'Classificação dos Créditos', 8),
(175, 'Metodologia da Pesquisa Jurídica', 1),
(175, 'Elaboração do Projeto de Pesquisa', 2),
(175, 'Revisão Bibliográfica', 3),
(175, 'Normas ABNT para Trabalhos Acadêmicos', 4),
(176, 'Intervenção do Estado na Propriedade', 1),
(176, 'Desapropriação', 2),
(176, 'Concessão e Permissão de Serviços Públicos', 3),
(176, 'Parcerias Público-Privadas (PPPs)', 4),
(176, 'Processo Administrativo (Lei 9.784/99)', 5),
(176, 'Improbidade Administrativa (Lei 14.230/21)', 6),
(176, 'Consórcios Públicos', 7),
(176, 'Agências Reguladoras', 8),
(177, 'Sistema Tributário Nacional', 1),
(177, 'Princípios Constitucionais Tributários', 2),
(177, 'Competência Tributária', 3),
(177, 'Limitações ao Poder de Tributar', 4),
(177, 'Imunidades Tributárias', 5),
(177, 'Espécies Tributárias', 6),
(177, 'Repartição das Receitas Tributárias', 7),
(177, 'Obrigação Tributária', 8),
(177, 'Crédito Tributário: Constituição e Extinção', 9),
(178, 'Prática em Direito Civil', 1),
(178, 'Prática em Direito Administrativo', 2),
(178, 'Petições e Recursos Avançados', 3),
(178, 'Atuação em Tribunais', 4),
(178, 'Casos Práticos Interdisciplinares', 5),
(179, 'Formação da Sociedade Brasileira', 1),
(179, 'Cidadania e Direitos Fundamentais', 2),
(179, 'Desigualdade Social e Políticas Públicas', 3),
(179, 'Movimentos Sociais e Participação Popular', 4),
(179, 'Diversidade e Inclusão', 5),
(180, 'Desenvolvimento do TCC', 1),
(180, 'Análise de Dados e Resultados', 2),
(180, 'Redação Final e Revisão', 3),
(180, 'Apresentação e Defesa do TCC', 4),
(181, 'Marco Civil da Internet', 1),
(181, 'Lei Geral de Proteção de Dados (LGPD)', 2),
(181, 'Crimes Cibernéticos', 3),
(181, 'Propriedade Intelectual na Internet', 4),
(181, 'E-commerce e Contratos Eletrônicos', 5),
(181, 'Responsabilidade dos Provedores', 6),
(181, 'Inteligência Artificial e Direito', 7),
(182, 'Fontes do Direito Internacional Público', 1),
(182, 'Sujeitos do Direito Internacional', 2),
(182, 'Organizações Internacionais (ONU, OEA)', 3),
(182, 'Tratados Internacionais', 4),
(182, 'Direito Internacional Privado', 5),
(182, 'Comércio Internacional', 6),
(182, 'Cooperação Jurídica Internacional', 7),
(182, 'Tribunal Penal Internacional', 8),
(183, 'Impostos Federais (IR, IPI, IOF)', 1),
(183, 'Impostos Estaduais (ICMS, ITCMD, IPVA)', 2),
(183, 'Impostos Municipais (IPTU, ISS, ITBI)', 3),
(183, 'Contribuições Sociais', 4),
(183, 'Contribuições de Intervenção no Domínio Econômico', 5),
(183, 'Taxas e Contribuições de Melhoria', 6),
(183, 'Processo Tributário: Administrativo e Judicial', 7),
(183, 'Execução Fiscal (Lei 6.830/80)', 8),
(184, 'Declaração Universal dos Direitos Humanos', 1),
(184, 'Sistema Interamericano de Direitos Humanos', 2),
(184, 'Direitos Humanos na CF/88', 3),
(184, 'Estatuto da Criança e do Adolescente (ECA)', 4),
(184, 'Estatuto do Idoso', 5),
(184, 'Estatuto da Pessoa com Deficiência', 6),
(184, 'Igualdade Racial e Combate à Discriminação', 7),
(184, 'Direitos dos Povos Indígenas', 8),
(185, 'Simulação de Audiências e Júri', 1),
(185, 'Prática em Direito Constitucional', 2),
(185, 'Mediação e Arbitragem na Prática', 3),
(185, 'Atuação em Causas Complexas', 4),
(185, 'Preparação para o Exame da OAB', 5);
