-- Add columns to VIDEO AULAS-NOVO for AI-generated content
ALTER TABLE "VIDEO AULAS-NOVO" 
ADD COLUMN IF NOT EXISTS sobre_aula TEXT,
ADD COLUMN IF NOT EXISTS flashcards JSONB,
ADD COLUMN IF NOT EXISTS questoes JSONB,
ADD COLUMN IF NOT EXISTS transcricao TEXT;