INSERT INTO oab_trilhas_topicos (materia_id, titulo, ordem, status) VALUES
(15, 'Princípios e Garantias do Processo Penal', 1, 'pendente'),
(15, 'Sistemas Processuais Penais', 2, 'pendente'),
(15, 'Lei Processual Penal no Tempo e no Espaço', 3, 'pendente'),
(15, 'Inquérito Policial', 4, 'pendente'),
(15, 'Interceptação Telefônica', 5, 'pendente'),
(15, 'Audiência de Custódia', 6, 'pendente'),
(15, 'Ação Penal', 7, 'pendente'),
(15, 'Competência Processual Penal', 8, 'pendente'),
(15, 'Prisões, Medidas Cautelares e Liberdade Provisória', 9, 'pendente'),
(15, 'Citações e Intimações', 10, 'pendente'),
(15, 'Disposições Gerais sobre Provas no Processo Penal', 11, 'pendente'),
(15, 'Provas no Processo Penal', 12, 'pendente'),
(15, 'Questões e Processos Incidentes', 13, 'pendente'),
(15, 'Membros da Justiça', 14, 'pendente'),
(15, 'Procedimento Comum, Júri e Procedimento Sumário', 15, 'pendente'),
(15, 'Sentença no Processo Penal', 16, 'pendente'),
(15, 'Nulidades no Processo Penal', 17, 'pendente'),
(15, 'Recursos no Processo Penal', 18, 'pendente'),
(15, 'Ação Civil Decorrente de Sentença Penal', 19, 'pendente'),
(15, 'Juizado Especial Criminal', 20, 'pendente'),
(15, 'Lei de Execução Penal', 21, 'pendente');