-- Inserir tópicos de Direito Penal na trilha OAB
INSERT INTO oab_trilhas_topicos (materia_id, titulo, ordem, status) VALUES
(14, 'Escolas Penais', 1, 'pendente'),
(14, 'Criminologia', 2, 'pendente'),
(14, 'Princípios Penais', 3, 'pendente'),
(14, 'Interpretação e Integração da Lei Penal', 4, 'pendente'),
(14, 'Lei Penal no Espaço e no Tempo', 5, 'pendente'),
(14, 'Conflito Aparente de Normas Penais', 6, 'pendente'),
(14, 'Teoria Geral do Delito', 7, 'pendente'),
(14, 'Iter Criminis', 8, 'pendente'),
(14, 'Teoria do Erro', 9, 'pendente'),
(14, 'Princípio da Insignificância', 10, 'pendente'),
(14, 'Imputabilidade e Concurso de Pessoas', 11, 'pendente'),
(14, 'Da Imputabilidade Penal e do Concurso de Pessoas', 12, 'pendente'),
(14, 'Concurso de Pessoas e Autoria Imediata', 13, 'pendente'),
(14, 'Teoria da Pena', 14, 'pendente'),
(14, 'Funções da Pena', 15, 'pendente'),
(14, 'Dosimetria da Pena', 16, 'pendente'),
(14, 'Concurso de Crimes', 17, 'pendente'),
(14, 'Suspensão Condicional da Pena e Livramento Condicional', 18, 'pendente'),
(14, 'Efeitos da Condenação e Reabilitação', 19, 'pendente'),
(14, 'Extinção da Punibilidade e Prescrição', 20, 'pendente'),
(14, 'Prescrição Penal', 21, 'pendente'),
(14, 'Medidas de Segurança', 22, 'pendente'),
(14, 'Crimes Contra a Pessoa', 23, 'pendente'),
(14, 'Crimes Contra a Vida', 24, 'pendente'),
(14, 'Crimes Contra a Honra', 25, 'pendente'),
(14, 'Direito Penal Sexual – Teoria Geral e Reflexos Típicos', 26, 'pendente'),
(14, 'Crimes contra a Dignidade Sexual', 27, 'pendente'),
(14, 'Crimes contra o Patrimônio', 28, 'pendente'),
(14, 'Crimes Contra a Propriedade Imaterial', 29, 'pendente'),
(14, 'Crimes Contra a Organização do Trabalho', 30, 'pendente'),
(14, 'Crimes Contra o Sentimento Religioso', 31, 'pendente'),
(14, 'Crimes Contra a Família', 32, 'pendente'),
(14, 'Crimes Contra a Fé Pública', 33, 'pendente'),
(14, 'Crimes praticados por Funcionário Público contra a Administração', 34, 'pendente'),
(14, 'Crimes Praticados por Particular Contra a Administração em Geral e Estrangeira', 35, 'pendente'),
(14, 'Crimes Praticados em Licitações e Contratos Administrativos', 36, 'pendente'),
(14, 'Crimes Contra a Administração da Justiça', 37, 'pendente'),
(14, 'Pacote Anticrime – Lei nº 13.964/2019', 38, 'pendente'),
(14, 'Legislação Penal Extravagante', 39, 'pendente'),
(14, 'Parte Criminal do Estatuto da Criança e do Adolescente', 40, 'pendente'),
(14, 'Estatuto do Desarmamento', 41, 'pendente'),
(14, 'Lei de Drogas', 42, 'pendente'),
(14, 'Crimes Ambientais e Responsabilidade', 43, 'pendente'),
(14, 'Responsabilidade Penal da Pessoa Jurídica', 44, 'pendente'),
(14, 'Direito Penal do Inimigo', 45, 'pendente'),
(14, 'Crítica ao Direito Penal do Inimigo', 46, 'pendente')
ON CONFLICT DO NOTHING;