-- Inserir tópicos para Direito Civil (materia_id = 9)
INSERT INTO public.oab_trilhas_topicos (materia_id, ordem, titulo, status)
VALUES
  (9, 1, 'Pessoas no Código Civil', 'pendente'),
  (9, 2, 'Direitos da Personalidade', 'pendente'),
  (9, 3, 'Bens no Código Civil', 'pendente'),
  (9, 4, 'Negócio Jurídico', 'pendente'),
  (9, 5, 'Bem de Família', 'pendente'),
  (9, 6, 'Teoria Geral dos Prazos e Prazos na LINDB', 'pendente'),
  (9, 7, 'Prescrição e Decadência', 'pendente'),
  (9, 8, 'Direito das Obrigações', 'pendente'),
  (9, 9, 'Transmissão das Obrigações', 'pendente'),
  (9, 10, 'Adimplemento e Extinção das Obrigações', 'pendente'),
  (9, 11, 'Teoria Geral dos Contratos', 'pendente'),
  (9, 12, 'Formação e Extinção dos Contratos', 'pendente'),
  (9, 13, 'Vícios Contratuais', 'pendente'),
  (9, 14, 'Contratos em Espécie', 'pendente'),
  (9, 15, 'Atos Unilaterais no Direito Civil', 'pendente'),
  (9, 16, 'Responsabilidade Civil', 'pendente'),
  (9, 17, 'Direitos Reais', 'pendente'),
  (9, 18, 'Posse', 'pendente'),
  (9, 19, 'Direito de Propriedade', 'pendente'),
  (9, 20, 'Direitos Reais: Propriedade, Superfície e Habitação', 'pendente'),
  (9, 21, 'Multipropriedade Imobiliária', 'pendente'),
  (9, 22, 'Alienação Fiduciária em Garantia', 'pendente'),
  (9, 23, 'Servidões, Usufruto e Uso', 'pendente'),
  (9, 24, 'Casamento e União Estável', 'pendente'),
  (9, 25, 'Guarda', 'pendente'),
  (9, 26, 'Regime de Bens', 'pendente'),
  (9, 27, 'Regime Matrimonial de Bens', 'pendente'),
  (9, 28, 'Alimentos', 'pendente'),
  (9, 29, 'Tutela, Curatela e Tomada de Decisão Apoiada', 'pendente'),
  (9, 30, 'Direito das Sucessões', 'pendente'),
  (9, 31, 'Direito Notarial', 'pendente'),
  (9, 32, 'Direito do Consumidor', 'pendente'),
  (9, 33, 'Aspectos Materiais da Lei do Superendividamento', 'pendente'),
  (9, 34, 'Consolidação da Propriedade no Regime da Lei 9.514/97', 'pendente')
ON CONFLICT DO NOTHING;