INSERT INTO "NOVIDADES" ("Dia", "Área", "Atualização") VALUES
('04/03/2026', 'Sistema', '🎨 Padronização visual dos ícones e títulos de todas as seções da Home'),
('04/03/2026', 'Sistema', '🔧 Seção Ferramentas reorganizada: Evelyn (IA) como segundo item após Vade Mecum'),
('05/03/2026', 'Sistema', '📱 Boletins movidos para o menu de rodapé (BottomNav) para acesso rápido'),
('05/03/2026', 'Biblioteca', '📖 Novo carrossel Biblioteca em Alta com livros de Estudos, Clássicos e OAB'),
('06/03/2026', 'Sistema', '⚡ Melhorias de performance no carregamento de imagens e cache instantâneo'),
('06/03/2026', 'Vade Mecum', '📜 Adicionada categoria Leis Complementares ao Vade Mecum 2026'),
('07/03/2026', 'Estudos', '🎓 Nova seção Temática Jurídica com JuriFlix e Documentários integrados'),
('08/03/2026', 'Sistema', '🖥️ Layout desktop otimizado com grades adaptativas de até 5 colunas'),
('09/03/2026', 'Vade Mecum', '📋 Proposições legislativas (PEC, PL, PLC) em grid compacto de 3 colunas'),
('10/03/2026', 'Sistema', '🎯 Personalização de atalhos na Home — escolha quais ferramentas exibir'),
('11/03/2026', 'Biblioteca', '📚 Biblioteca de Política com filtros por orientação: Esquerda, Centro, Direita'),
('12/03/2026', 'IA', '🤖 Evelyn agora acessível direto pelo container de Ferramentas na Home'),
('13/03/2026', 'Sistema', '🔔 Sistema de notificações redesenhado com categorias visuais por área'),
('14/03/2026', 'Vade Mecum', '⚖️ Aba Explicações adicionada ao Vade Mecum para conteúdo didático'),
('15/03/2026', 'Estudos', '📝 Metodologias de estudo (Cornell, Feynman, Conceitos) com timeline serpentina'),
('16/03/2026', 'Sistema', '🎨 Novo design dos cards OAB com visual premium e sombras refinadas'),
('17/03/2026', 'Design', '✨ Tipografia padronizada em todas as seções — fonte do sistema em títulos'),
('17/03/2026', 'Sistema', '🎠 Carrossel de Clássicos suavizado com animação GPU-accelerated'),
('18/03/2026', 'Design', '🎨 Redesign completo da aba Novidades com cards coloridos por data'),
('18/03/2026', 'Vade Mecum', '📜 Vade Mecum 2026 atualizado com novas leis publicadas no Diário Oficial');