
-- ESTÁCIO (id=4)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(4,1,'Ciência Política e Teoria do Estado','Instituições políticas'),(4,1,'Filosofia','Fundamentos filosóficos'),(4,1,'Fundamentos Antropológicos e Sociológicos','Bases antropológicas'),(4,1,'Introdução ao Estudo do Direito','Conceitos fundamentais'),(4,1,'Língua Portuguesa','Comunicação jurídica'),
(4,2,'Direito Civil – Parte Geral','Pessoas, bens'),(4,2,'Teoria Geral do Crime','Tipicidade, ilicitude'),(4,2,'Teoria da Constituição','Poder constituinte'),(4,2,'Economia','Fundamentos econômicos'),(4,2,'Hermenêutica Jurídica','Interpretação do Direito'),
(4,3,'Direito Civil – Obrigações','Teoria das obrigações'),(4,3,'Direito Constitucional','Direitos fundamentais'),(4,3,'Direito Penal – Teoria da Pena','Aplicação da pena'),(4,3,'Teoria Geral do Processo','Jurisdição, ação'),(4,3,'Sociologia Jurídica','Sociedade e Direito'),
(4,4,'Direito Civil – Contratos','Teoria dos contratos'),(4,4,'Direito Penal – Crimes contra a Pessoa','Homicídio, lesão'),(4,4,'Direito Processual Civil – Conhecimento','Procedimento comum'),(4,4,'Direito do Trabalho – Individual','Contrato de trabalho'),(4,4,'Direito Administrativo I','Princípios, atos'),
(4,5,'Direito Civil – Responsabilidade Civil','Responsabilidade'),(4,5,'Direito Penal – Crimes contra o Patrimônio','Furto, roubo'),(4,5,'Direito Processual Civil – Execução','Cumprimento de sentença'),(4,5,'Direito Processual Penal I','Inquérito, ação penal'),(4,5,'Direito Empresarial','Teoria da empresa'),
(4,6,'Direito Civil – Coisas','Posse, propriedade'),(4,6,'Direito do Consumidor','CDC'),(4,6,'Direito Processual Civil – Recursos','Sistema recursal'),(4,6,'Direito Processual Penal II','Provas, sentença'),(4,6,'Direito Administrativo II','Serviços públicos'),(4,6,'Direito Tributário I','Sistema tributário'),
(4,7,'Direito Civil – Família','Casamento, filiação'),(4,7,'Direito Societário','Sociedades empresárias'),(4,7,'Direito do Trabalho – Coletivo','Sindicatos, greve'),(4,7,'Direito Tributário II','Obrigação tributária'),(4,7,'Direito Previdenciário','Seguridade social'),(4,7,'Prática Jurídica I','Prática simulada'),
(4,8,'Direito Civil – Sucessões','Herança, testamento'),(4,8,'Direito Processual do Trabalho','Processo trabalhista'),(4,8,'Falência e Recuperação Judicial','Processo falimentar'),(4,8,'Direito Internacional Público','Sujeitos, fontes'),(4,8,'Ética Profissional e Estatuto da OAB','Deontologia'),(4,8,'Prática Jurídica II','Prática forense'),
(4,9,'Direito Ambiental','Tutela ambiental'),(4,9,'Direito Eleitoral','Sistema eleitoral'),(4,9,'Direito Internacional Privado','Conflito de leis'),(4,9,'Legislação Penal Especial','Leis extravagantes'),(4,9,'Prática Jurídica III','Prática trabalhista'),(4,9,'TCC I','Projeto de monografia'),
(4,10,'Direitos Humanos','Proteção internacional'),(4,10,'Direito Digital','Marco Civil, LGPD'),(4,10,'Mediação e Arbitragem','Métodos alternativos'),(4,10,'Direito da Criança e do Adolescente','ECA'),(4,10,'Prática Jurídica IV','Prática especializada'),(4,10,'TCC II','Defesa da monografia');

-- UNINOVE (id=5)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(5,1,'Introdução ao Estudo do Direito','Fontes, norma jurídica'),(5,1,'Ciência Política e Teoria do Estado','Formas de governo'),(5,1,'Filosofia Geral e Jurídica','Correntes filosóficas'),(5,1,'Sociologia Geral e Jurídica','Fenômeno social'),(5,1,'Economia','Micro e macroeconomia'),(5,1,'Comunicação e Expressão','Linguagem jurídica'),
(5,2,'Direito Civil – Parte Geral','Pessoas, bens'),(5,2,'Direito Constitucional I','Teoria da Constituição'),(5,2,'Direito Penal I – Teoria do Crime','Conceito de crime'),(5,2,'História do Direito','Evolução histórica'),(5,2,'Psicologia Jurídica','Aspectos psicológicos'),
(5,3,'Direito Civil – Obrigações','Teoria das obrigações'),(5,3,'Direito Constitucional II','Direitos fundamentais'),(5,3,'Direito Penal II – Teoria da Pena','Aplicação da pena'),(5,3,'Teoria Geral do Processo','Jurisdição, ação'),(5,3,'Hermenêutica Jurídica','Interpretação do Direito'),
(5,4,'Direito Civil – Contratos','Teoria dos contratos'),(5,4,'Direito Penal III – Crimes em Espécie','Crimes contra a pessoa'),(5,4,'Direito Processual Civil I','Procedimento comum'),(5,4,'Direito do Trabalho I','Contrato de trabalho'),(5,4,'Direito Administrativo I','Princípios, organização'),
(5,5,'Direito Civil – Responsabilidade Civil','Dano, nexo causal'),(5,5,'Direito Penal IV – Legislação Especial','Leis extravagantes'),(5,5,'Direito Processual Civil II','Recursos, execução'),(5,5,'Direito do Trabalho II','Direito coletivo'),(5,5,'Direito Administrativo II','Licitações'),
(5,6,'Direito Civil – Coisas','Posse, propriedade'),(5,6,'Direito Empresarial I','Teoria da empresa'),(5,6,'Direito Processual Penal I','Ação penal'),(5,6,'Direito Tributário I','Sistema tributário'),(5,6,'Direito do Consumidor','CDC'),
(5,7,'Direito Civil – Família','Casamento, filiação'),(5,7,'Direito Empresarial II','Títulos de crédito'),(5,7,'Direito Processual Penal II','Provas, sentença'),(5,7,'Direito Tributário II','Crédito tributário'),(5,7,'Prática Jurídica I','Prática cível'),
(5,8,'Direito Civil – Sucessões','Herança, testamento'),(5,8,'Direito Processual do Trabalho','Processo trabalhista'),(5,8,'Direito Previdenciário','Seguridade social'),(5,8,'Direito Internacional Público','Tratados'),(5,8,'Prática Jurídica II','Prática penal'),
(5,9,'Direito Ambiental','Tutela ambiental'),(5,9,'Direito Eleitoral','Processo eleitoral'),(5,9,'Ética e Estatuto da OAB','Deontologia'),(5,9,'Direito Internacional Privado','Cooperação'),(5,9,'Prática Jurídica III','Prática trabalhista'),(5,9,'TCC I','Projeto'),
(5,10,'Direitos Humanos','Proteção internacional'),(5,10,'Direito Digital','Marco Civil, LGPD'),(5,10,'Mediação e Conciliação','Métodos autocompositivos'),(5,10,'Direito da Criança e do Adolescente','ECA'),(5,10,'Prática Jurídica IV','Prática especializada'),(5,10,'TCC II','Defesa do TCC');

-- UNOPAR (id=6)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(6,1,'Cultura Digital','Tecnologias digitais'),(6,1,'Fundamentos Históricos e Introdução ao Estudo do Direito','História e conceitos'),(6,1,'Psicologia Aplicada ao Direito','Aspectos psicológicos'),(6,1,'Teoria da Argumentação Jurídica','Lógica, retórica'),(6,1,'Teoria Geral do Direito Constitucional','Poder constituinte'),
(6,2,'Direito Civil – Parte Geral','Pessoas, bens'),(6,2,'Direito Individual do Trabalho','Contrato de trabalho'),(6,2,'Teoria Geral do Processo','Jurisdição, ação'),(6,2,'Teoria Jurídica do Direito Penal','Conceito de crime'),
(6,3,'Direito Civil – Obrigações','Teoria das obrigações'),(6,3,'Direito Constitucional','Direitos fundamentais'),(6,3,'Direito Penal – Teoria das Penas e Execução Penal','Aplicação das penas'),(6,3,'Direito Processual Civil – Conhecimento','Procedimento comum'),
(6,4,'Direito Ambiental','Tutela ambiental'),(6,4,'Direito Civil – Contratos','Contratos em geral'),(6,4,'Direito Coletivo do Trabalho e Tutelas Coletivas','Sindicatos'),(6,4,'Direito Econômico e Financeiro','Intervenção estatal'),
(6,5,'Direito Penal – Dos Crimes em Espécie','Crimes contra a pessoa'),(6,5,'Direito Processual Civil – Execução','Execução'),(6,5,'Direito Processual do Trabalho','Processo trabalhista'),(6,5,'Filosofia e Sociologia do Direito','Correntes filosóficas'),
(6,6,'Direito Administrativo','Princípios, organização'),(6,6,'Direito Civil – Coisas','Posse, propriedade'),(6,6,'Direito Empresarial e Societário','Sociedades'),(6,6,'Direito Previdenciário','Seguridade social'),(6,6,'Responsabilidade Civil e Direito do Consumidor','Dano, CDC'),
(6,7,'Direito Civil – Família','Casamento, filiação'),(6,7,'Direito Processual Civil – Recursos','Sistema recursal'),(6,7,'Ética Profissional','Deontologia'),(6,7,'Prática Jurídica I','Prática cível'),(6,7,'Meios Integrados de Resolução de Conflitos','Mediação'),
(6,8,'Direito Civil – Sucessões','Herança, testamento'),(6,8,'Direito Processual Penal','Inquérito, ação penal'),(6,8,'Prática Jurídica II','Prática penal'),(6,8,'Títulos de Crédito e Recuperação e Falência','Títulos, falência'),(6,8,'TCC I','Projeto de pesquisa'),
(6,9,'Direito Administrativo – Administração Pública','Serviços públicos'),(6,9,'Direito Tributário – Constitucional Tributário','Sistema tributário'),(6,9,'Prática Jurídica III','Prática trabalhista'),(6,9,'Sociedade Brasileira e Cidadania','Formação social'),(6,9,'TCC II','Monografia'),
(6,10,'Direito Cibernético','Crimes digitais, LGPD'),(6,10,'Direito Internacional','Público e privado'),(6,10,'Direito Tributário – Tributos em Espécie','Impostos, taxas'),(6,10,'Direitos Humanos, Inclusão e Idoso','Proteção especial'),(6,10,'Prática Jurídica IV','Prática especializada');

-- PUC-SP (id=7)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(7,1,'Introdução ao Estudo do Direito','Conceitos fundamentais'),(7,1,'Ciência Política e Teoria do Estado','Formas de governo'),(7,1,'Filosofia do Direito I','Fundamentos filosóficos'),(7,1,'Sociologia Jurídica','Relações sociais'),(7,1,'Economia Política','Teoria econômica'),(7,1,'História do Direito','Evolução histórica'),
(7,2,'Direito Civil I – Parte Geral','Pessoas, bens'),(7,2,'Direito Constitucional I','Teoria da Constituição'),(7,2,'Direito Penal I – Teoria do Crime','Conceito de crime'),(7,2,'Filosofia do Direito II','Justiça, moral'),(7,2,'Antropologia Jurídica','Dimensões culturais'),
(7,3,'Direito Civil II – Obrigações','Teoria das obrigações'),(7,3,'Direito Constitucional II','Direitos fundamentais'),(7,3,'Direito Penal II – Teoria da Pena','Aplicação da pena'),(7,3,'Teoria Geral do Processo','Jurisdição, competência'),(7,3,'Direito do Trabalho I','Contrato de trabalho'),
(7,4,'Direito Civil III – Contratos','Teoria dos contratos'),(7,4,'Direito Penal III – Crimes em Espécie','Crimes contra a pessoa'),(7,4,'Direito Processual Civil I','Procedimento comum'),(7,4,'Direito Administrativo I','Princípios, atos'),(7,4,'Direito do Trabalho II','Direito coletivo'),
(7,5,'Direito Civil IV – Responsabilidade Civil','Dano, nexo causal'),(7,5,'Direito Penal IV – Legislação Especial','Leis extravagantes'),(7,5,'Direito Processual Civil II','Recursos, execução'),(7,5,'Direito Administrativo II','Licitações'),(7,5,'Direito Processual Penal I','Inquérito'),
(7,6,'Direito Civil V – Coisas','Posse, propriedade'),(7,6,'Direito Empresarial I','Teoria da empresa'),(7,6,'Direito Processual Civil III','Procedimentos especiais'),(7,6,'Direito Processual Penal II','Provas, sentença'),(7,6,'Direito Tributário I','Sistema tributário'),
(7,7,'Direito Civil VI – Família','Casamento, parentesco'),(7,7,'Direito Empresarial II','Títulos de crédito'),(7,7,'Direito Tributário II','Obrigação tributária'),(7,7,'Direito Processual do Trabalho','Processo trabalhista'),(7,7,'Direito Internacional Público','Sujeitos, fontes'),(7,7,'Prática Jurídica I','Prática cível'),
(7,8,'Direito Civil VII – Sucessões','Herança, testamento'),(7,8,'Direito Previdenciário','Seguridade social'),(7,8,'Direito Internacional Privado','Conflito de leis'),(7,8,'Ética e Estatuto da OAB','Deontologia'),(7,8,'Prática Jurídica II','Prática penal'),
(7,9,'Direito Ambiental','Tutela ambiental'),(7,9,'Direito do Consumidor','Relações de consumo'),(7,9,'Direito Eleitoral','Sistema eleitoral'),(7,9,'Direitos Humanos','Proteção internacional'),(7,9,'Prática Jurídica III','Prática trabalhista'),(7,9,'TCC I','Projeto de monografia'),
(7,10,'Direito Digital e LGPD','Marco Civil, dados'),(7,10,'Mediação e Arbitragem','Métodos alternativos'),(7,10,'Direito da Criança e do Adolescente','ECA'),(7,10,'Prática Jurídica IV','Prática especializada'),(7,10,'TCC II','Defesa do trabalho');

-- MACKENZIE (id=8) - 8 etapas
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(8,1,'Antropologia Jurídica','Dimensões culturais'),(8,1,'Ciência Política','Instituições políticas'),(8,1,'História do Direito','Evolução histórica'),(8,1,'Teoria Geral do Direito','Fontes, norma jurídica'),(8,1,'Pessoas e Bens','Parte geral Civil'),(8,1,'Linguagem Jurídica','Redação jurídica'),(8,1,'Economia Política','Fundamentos econômicos'),(8,1,'Lógica Jurídica','Raciocínio lógico'),(8,1,'Ciência, Tecnologia e Sociedade no Direito','Tecnologia e Direito'),(8,1,'Ética e Cidadania','Valores éticos'),
(8,2,'Criminologia e Teoria Geral do Crime','Estudo do crime'),(8,2,'Fatos Jurídicos','Negócio jurídico'),(8,2,'Filosofia do Direito','Correntes filosóficas'),(8,2,'Sociologia do Direito','Sociedade e Direito'),(8,2,'Retórica e Argumentação','Persuasão e oratória'),(8,2,'Teoria da Constituição','Poder constituinte'),(8,2,'Metodologia da Pesquisa Jurídica','Métodos de pesquisa'),(8,2,'Direito Internacional Público','Sujeitos, fontes'),
(8,3,'Direito das Obrigações e Responsabilidade Civil','Obrigações'),(8,3,'Direitos Humanos e Fundamentais','Sistema de proteção'),(8,3,'Direito de Empresa','Teoria da empresa'),(8,3,'Teoria Geral da Pena','Aplicação, dosimetria'),(8,3,'Teoria Geral do Processo','Jurisdição, ação'),(8,3,'Direito Internacional Privado','Conflito de leis'),(8,3,'Direito da Criança, do Adolescente, do Idoso e da Inclusão','Estatutos protetivos'),
(8,4,'Contratos e Responsabilidade Contratual','Teoria dos contratos'),(8,4,'Sociedades Empresárias','Tipos societários'),(8,4,'Organização do Estado e Separação de Poderes','Federalismo'),(8,4,'Crimes contra a Pessoa e a Dignidade Sexual','Homicídio, crimes sexuais'),(8,4,'Processo de Conhecimento','Procedimento cível'),(8,4,'Prática Legislativa','Processo legislativo'),(8,4,'Sistemas de Investigação e Ritos Processuais','Inquérito'),
(8,5,'Audiência, Sentença e Recursos Cíveis','Instrução, recursos'),(8,5,'Controle de Constitucionalidade','ADI, ADC, ADPF'),(8,5,'Crimes contra o Patrimônio','Furto, roubo'),(8,5,'Direito das Coisas','Posse, propriedade'),(8,5,'Obrigações Mercantis','Títulos de crédito'),(8,5,'Jurisdição e Medidas Cautelares Penais','Jurisdição penal'),(8,5,'Direito Econômico','Intervenção na economia'),(8,5,'Princípios e Organização da Administração Pública','Direito Administrativo I'),
(8,6,'Cumprimento de Sentença e Execução Civil','Execução civil'),(8,6,'Direito de Família','Casamento, união estável'),(8,6,'Crimes contra a Administração e a Fé Pública','Crimes funcionais'),(8,6,'Teoria Geral da Prova e Decisão Penal','Provas penais'),(8,6,'Ato Administrativo e Controle da Administração','Direito Administrativo II'),(8,6,'Direito da Inovação','Propriedade intelectual'),(8,6,'Direito Individual do Trabalho','Contrato de trabalho'),
(8,7,'Procedimentos Especiais e Tutelas de Urgência','Procedimentos especiais'),(8,7,'Recursos e Execução da Sentença Penal','Recursos penais'),(8,7,'Direito da Seguridade Social','Previdência'),(8,7,'Direito Coletivo do Trabalho','Sindicatos, greve'),(8,7,'Agentes, Contratações e Serviços Públicos','Licitações'),(8,7,'Sistema Tributário Constitucional','Competência, imunidades'),(8,7,'Legislação Penal Especial','Leis extravagantes'),(8,7,'Direito das Sucessões','Herança, testamento'),(8,7,'Prática Cível','Prática forense cível'),(8,7,'Prática Penal','Prática forense penal'),
(8,8,'Ética Profissional','Deontologia e OAB'),(8,8,'Direito Eleitoral','Sistema eleitoral'),(8,8,'Direito Processual do Trabalho','Processo trabalhista'),(8,8,'Falência e Recuperação Judicial','Processo falimentar'),(8,8,'Relações Estatais, Bens e Intervenções','Domínio público'),(8,8,'Teoria Geral da Obrigação Tributária','Obrigação tributária'),(8,8,'Prática da Seguridade Social','Prática previdenciária'),(8,8,'Prática Trabalhista','Prática trabalhista'),(8,8,'Direito Ambiental','Tutela ambiental'),(8,8,'Biodireito','Biotecnologia e Direito');

-- UFMG (id=9)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(9,1,'Teoria do Estado I','Formas de Estado'),(9,1,'Introdução ao Estudo do Direito I','Fontes, norma jurídica'),(9,1,'Economia Política','Fundamentos econômicos'),(9,1,'Sociologia Geral e Jurídica','Fenômeno social'),(9,1,'História do Direito','Formação histórica'),
(9,2,'Teoria do Estado II','Democracia, partidos'),(9,2,'Introdução ao Estudo do Direito II','Hermenêutica'),(9,2,'Direito Civil – Parte Geral','Pessoas, bens'),(9,2,'Direito Penal I – Teoria do Crime','Conceito de crime'),(9,2,'Filosofia do Direito I','Correntes jusfilosóficas'),
(9,3,'Teoria da Constituição','Poder constituinte'),(9,3,'Direito Civil – Obrigações','Teoria das obrigações'),(9,3,'Direito Penal II – Ilicitude e Culpabilidade','Causas de exclusão'),(9,3,'Filosofia do Direito II','Justiça, ética'),(9,3,'Direito do Trabalho I','Contrato de trabalho'),
(9,4,'Direito Constitucional I','Direitos fundamentais'),(9,4,'Direito Civil – Contratos','Teoria dos contratos'),(9,4,'Direito Penal III – Teoria da Pena','Aplicação, dosimetria'),(9,4,'Teoria Geral do Processo','Jurisdição, ação'),(9,4,'Direito do Trabalho II','Direito coletivo'),
(9,5,'Direito Constitucional II','Organização do Estado'),(9,5,'Direito Civil – Responsabilidade Civil','Dano, nexo causal'),(9,5,'Direito Penal IV – Crimes em Espécie','Crimes contra a pessoa'),(9,5,'Direito Processual Civil I','Procedimento comum'),(9,5,'Direito Administrativo I','Princípios, organização'),
(9,6,'Direito Civil – Coisas','Posse, propriedade'),(9,6,'Direito Empresarial I','Teoria da empresa'),(9,6,'Direito Processual Civil II','Recursos, execução'),(9,6,'Direito Processual Penal I','Inquérito, ação penal'),(9,6,'Direito Administrativo II','Licitações'),
(9,7,'Direito Civil – Família','Casamento, parentesco'),(9,7,'Direito Empresarial II','Títulos de crédito'),(9,7,'Direito Processual Civil III','Procedimentos especiais'),(9,7,'Direito Processual Penal II','Provas, sentença'),(9,7,'Direito Tributário I','Sistema tributário'),(9,7,'Direito Internacional Público','Fontes, sujeitos'),
(9,8,'Direito Civil – Sucessões','Herança, testamento'),(9,8,'Direito Tributário II','Crédito tributário'),(9,8,'Direito Processual do Trabalho','Processo trabalhista'),(9,8,'Direito Previdenciário','Seguridade social'),(9,8,'Medicina Legal','Perícia, traumatologia'),
(9,9,'Direito Ambiental','Tutela ambiental'),(9,9,'Direito do Consumidor','CDC'),(9,9,'Direito Internacional Privado','Conflito de leis'),(9,9,'Ética Profissional','Deontologia e OAB'),(9,9,'Prática Jurídica I','Prática simulada'),
(9,10,'Direitos Humanos','Proteção internacional'),(9,10,'Direito Eleitoral','Sistema eleitoral'),(9,10,'Legislação Penal Especial','Leis extravagantes'),(9,10,'Prática Jurídica II','Prática forense'),(9,10,'TCC','Trabalho de conclusão');

-- UERJ (id=10)
INSERT INTO faculdade_disciplinas (universidade_id, semestre, nome, ementa) VALUES
(10,1,'Introdução ao Estudo do Direito I','Fontes, normas'),(10,1,'História do Direito','Evolução histórica'),(10,1,'Economia Política I','Micro e macroeconomia'),(10,1,'Direito e Pensamento Político I','Filosofia política'),(10,1,'Introdução à Sociologia Jurídica','Relações sociais'),
(10,2,'Introdução ao Estudo do Direito II','Hermenêutica'),(10,2,'Direito Civil I – Parte Geral','Pessoas, bens'),(10,2,'Direito Constitucional I','Teoria da Constituição'),(10,2,'Direito Penal I','Teoria do crime'),(10,2,'Direito e Pensamento Político II','Teorias contemporâneas'),
(10,3,'Direito Civil II – Obrigações','Teoria das obrigações'),(10,3,'Direito Constitucional II','Direitos fundamentais'),(10,3,'Direito Penal II','Ilicitude, culpabilidade'),(10,3,'Teoria Geral do Processo','Jurisdição, ação'),(10,3,'Filosofia do Direito','Correntes jusfilosóficas'),
(10,4,'Direito Civil III – Contratos','Teoria dos contratos'),(10,4,'Direito Constitucional III','Organização do Estado'),(10,4,'Direito Penal III – Crimes em Espécie','Crimes contra a pessoa'),(10,4,'Direito Processual Civil I','Procedimento comum'),(10,4,'Direito do Trabalho I','Contrato de trabalho'),
(10,5,'Direito Civil IV – Responsabilidade Civil','Dano, nexo causal'),(10,5,'Direito Penal IV – Crimes contra o Patrimônio','Furto, roubo'),(10,5,'Direito Processual Civil II','Recursos, execução'),(10,5,'Direito Administrativo I','Princípios, organização'),(10,5,'Direito do Trabalho II','Direito coletivo'),
(10,6,'Direito Civil V – Coisas','Posse, propriedade'),(10,6,'Direito Empresarial I','Teoria da empresa'),(10,6,'Direito Processual Civil III','Procedimentos especiais'),(10,6,'Direito Processual Penal I','Inquérito, ação penal'),(10,6,'Direito Administrativo II','Serviços públicos'),
(10,7,'Direito Civil VI – Família','Casamento, filiação'),(10,7,'Direito Empresarial II','Sociedades, títulos'),(10,7,'Direito Processual Penal II','Provas, sentença'),(10,7,'Direito Tributário I','Sistema tributário'),(10,7,'Direito Internacional Público','Fontes, sujeitos'),
(10,8,'Direito Civil VII – Sucessões','Herança, testamento'),(10,8,'Direito Tributário II','Obrigação tributária'),(10,8,'Direito Processual do Trabalho','Processo trabalhista'),(10,8,'Direito Previdenciário','Seguridade social'),(10,8,'Direito Internacional Privado','Conflito de leis'),
(10,9,'Direito Ambiental','Tutela ambiental'),(10,9,'Direito do Consumidor','Relações de consumo'),(10,9,'Ética Profissional','Deontologia e OAB'),(10,9,'Direitos Humanos','Proteção internacional'),(10,9,'Prática Jurídica I','Prática simulada'),
(10,10,'Direito Eleitoral','Sistema eleitoral'),(10,10,'Legislação Penal Especial','Leis extravagantes'),(10,10,'Falência e Recuperação de Empresas','Processo falimentar'),(10,10,'Prática Jurídica II','Prática forense'),(10,10,'Medicina Legal','Perícia forense');

-- Ativar todas e ajustar Mackenzie
UPDATE faculdade_universidades SET ativo = true WHERE id IN (4, 5, 6, 7, 8, 9, 10);
UPDATE faculdade_universidades SET total_semestres = 8 WHERE id = 8;
