
-- Inserir tópicos para Direito Processual Civil (materia_id = 10)
INSERT INTO oab_trilhas_topicos (materia_id, titulo, ordem, status) VALUES
(10, 'Teoria Geral e Princípios do Processo', 1, 'pendente'),
(10, 'Jurisdição', 2, 'pendente'),
(10, 'Competência Processual', 3, 'pendente'),
(10, 'Capacidade e Sujeitos Processuais', 4, 'pendente'),
(10, 'Partes e Procuradores', 5, 'pendente'),
(10, 'Litisconsórcio', 6, 'pendente'),
(10, 'Intervenção de Terceiros', 7, 'pendente'),
(10, 'Juiz e Auxiliares da Justiça', 8, 'pendente'),
(10, 'Formas Alternativas de Resolução de Disputas', 9, 'pendente'),
(10, 'Mediação', 10, 'pendente'),
(10, 'Arbitragem', 11, 'pendente'),
(10, 'Atos Processuais', 12, 'pendente'),
(10, 'Comunicação dos Atos Processuais', 13, 'pendente'),
(10, 'Atos e Nulidades Processuais', 14, 'pendente'),
(10, 'Pressupostos Processuais', 15, 'pendente'),
(10, 'Formação, Suspensão e Extinção do Processo', 16, 'pendente'),
(10, 'Petição Inicial', 17, 'pendente'),
(10, 'Tutela Provisória', 18, 'pendente'),
(10, 'Tutelas Provisórias na Prática', 19, 'pendente'),
(10, 'Respostas e Comportamentos do Réu', 20, 'pendente'),
(10, 'Provas no Processo Civil', 21, 'pendente'),
(10, 'Procedimento Comum', 22, 'pendente'),
(10, 'Vícios Processuais', 23, 'pendente'),
(10, 'Sentença e Coisa Julgada', 24, 'pendente'),
(10, 'Cumprimento de Sentença', 25, 'pendente'),
(10, 'Processo de Execução: Introdução e Princípios', 26, 'pendente'),
(10, 'Espécies de Execução', 27, 'pendente'),
(10, 'Embargos, Suspensão e Extinção da Execução', 28, 'pendente'),
(10, 'Teoria Geral dos Recursos', 29, 'pendente'),
(10, 'Recursos no Processo Civil', 30, 'pendente'),
(10, 'Processos de Competência Originária dos Tribunais', 31, 'pendente'),
(10, 'Ação Rescisória', 32, 'pendente'),
(10, 'Juizado Especial Cível', 33, 'pendente'),
(10, 'Juizado Especial Federal', 34, 'pendente'),
(10, 'Juizado Especial da Fazenda Pública', 35, 'pendente'),
(10, 'Ação de Consignação em Pagamento', 36, 'pendente'),
(10, 'Ação de Exigir Contas', 37, 'pendente'),
(10, 'Ação Monitória', 38, 'pendente'),
(10, 'Ações Possessórias', 39, 'pendente'),
(10, 'Embargos de Terceiro e Oposição', 40, 'pendente'),
(10, 'Inventário e Partilha', 41, 'pendente'),
(10, 'Processos Estruturais', 42, 'pendente'),
(10, 'Direito Processual Coletivo', 43, 'pendente'),
(10, 'Direito Processual do Consumidor', 44, 'pendente'),
(10, 'Aspectos Processuais da Lei do Superendividamento', 45, 'pendente');
