
CREATE TABLE "MAPAS_MENTAIS_GERADOS" (
  id BIGSERIAL PRIMARY KEY,
  area TEXT NOT NULL,
  tema TEXT NOT NULL,
  dados_json JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(area, tema)
);

ALTER TABLE "MAPAS_MENTAIS_GERADOS" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all read" ON "MAPAS_MENTAIS_GERADOS" FOR SELECT USING (true);
CREATE POLICY "Allow all insert" ON "MAPAS_MENTAIS_GERADOS" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update" ON "MAPAS_MENTAIS_GERADOS" FOR UPDATE USING (true);
CREATE POLICY "Allow all delete" ON "MAPAS_MENTAIS_GERADOS" FOR DELETE USING (true);
