
-- Faculdade de Direito (30 temas)
INSERT INTO blogger_faculdade (ordem, titulo, descricao_curta) VALUES
(1, 'O que é o curso de Direito?', 'Visão geral sobre a graduação em Direito no Brasil'),
(2, 'Grade curricular do curso de Direito', 'Disciplinas obrigatórias e optativas ao longo dos 5 anos'),
(3, 'Como escolher a faculdade de Direito ideal', 'Critérios para selecionar a melhor instituição'),
(4, 'Diferença entre bacharelado e licenciatura em Direito', 'Entenda os tipos de formação jurídica'),
(5, 'Estágio obrigatório em Direito', 'Como funciona o Núcleo de Prática Jurídica (NPJ)'),
(6, 'TCC em Direito: como escolher o tema', 'Dicas para a monografia de conclusão de curso'),
(7, 'As áreas do Direito mais promissoras', 'Quais especializações estão em alta no mercado'),
(8, 'Direito Civil na faculdade', 'O que você aprende sobre relações civis'),
(9, 'Direito Penal na graduação', 'Fundamentos do sistema penal brasileiro'),
(10, 'Direito Constitucional na faculdade', 'A base de todo o ordenamento jurídico'),
(11, 'Direito do Trabalho: o que se estuda', 'Relações trabalhistas e CLT na graduação'),
(12, 'Direito Administrativo na faculdade', 'Administração pública e seus princípios'),
(13, 'Direito Tributário: impostos e tributos', 'Entendendo o sistema tributário nacional'),
(14, 'Direito Processual Civil', 'Como funcionam os processos judiciais cíveis'),
(15, 'Direito Processual Penal', 'O procedimento criminal no Brasil'),
(16, 'Direito Empresarial na graduação', 'Sociedades, contratos e falência'),
(17, 'Filosofia do Direito', 'As bases filosóficas do pensamento jurídico'),
(18, 'Sociologia Jurídica', 'O Direito e suas relações com a sociedade'),
(19, 'Hermenêutica Jurídica', 'A arte de interpretar as normas'),
(20, 'Direito Internacional na faculdade', 'Relações entre países e tratados'),
(21, 'Direitos Humanos na graduação', 'Proteção da dignidade humana'),
(22, 'Direito Ambiental: introdução', 'Proteção do meio ambiente pelo Direito'),
(23, 'Direito Digital e novas tecnologias', 'A fronteira mais moderna do Direito'),
(24, 'Como funciona a OAB para estudantes', 'Preparação para o Exame de Ordem'),
(25, 'Intercâmbio acadêmico em Direito', 'Estudar Direito no exterior'),
(26, 'Pesquisa científica em Direito', 'Iniciação científica e produção acadêmica'),
(27, 'Competições jurídicas (Moot Courts)', 'Simulações de tribunais e competições'),
(28, 'Pós-graduação em Direito', 'Especialização, mestrado e doutorado'),
(29, 'Mercado de trabalho para recém-formados', 'Primeiros passos após a graduação'),
(30, 'Ética profissional e deontologia jurídica', 'O código de ética do advogado');

-- STF (30 temas)
INSERT INTO blogger_stf (ordem, titulo, descricao_curta) VALUES
(1, 'O que é o Supremo Tribunal Federal?', 'História e função do STF no Brasil'),
(2, 'Composição do STF', 'Os 11 ministros e como são escolhidos'),
(3, 'Como um ministro é nomeado para o STF', 'O processo de indicação e sabatina'),
(4, 'O papel do Presidente do STF', 'Funções e responsabilidades do presidente'),
(5, 'Competências do STF', 'O que o Supremo pode e não pode julgar'),
(6, 'Ação Direta de Inconstitucionalidade (ADI)', 'Como funciona o controle concentrado'),
(7, 'Ação Declaratória de Constitucionalidade (ADC)', 'Confirmando a validade de leis'),
(8, 'ADPF: Arguição de Descumprimento', 'Proteção de preceitos fundamentais'),
(9, 'Mandado de Injunção no STF', 'Quando falta uma lei regulamentadora'),
(10, 'Habeas Corpus no STF', 'Proteção da liberdade de locomoção'),
(11, 'Recurso Extraordinário', 'Quando um caso chega ao Supremo'),
(12, 'Repercussão Geral', 'Filtro para recursos extraordinários'),
(13, 'Súmulas Vinculantes', 'Decisões que vinculam todo o Judiciário'),
(14, 'Plenário do STF', 'Como funciona a sessão plenária'),
(15, 'Turmas do STF', 'A divisão em Primeira e Segunda Turma'),
(16, 'Julgamento virtual no STF', 'A modernização dos julgamentos'),
(17, 'O STF e o controle de constitucionalidade', 'Guardião da Constituição Federal'),
(18, 'Casos históricos do STF', 'Julgamentos que marcaram a história'),
(19, 'O STF e os direitos fundamentais', 'Proteção das garantias constitucionais'),
(20, 'Amicus Curiae no STF', 'A participação da sociedade nos julgamentos'),
(21, 'Audiências públicas no STF', 'Quando o Supremo ouve a sociedade'),
(22, 'O STF e a separação de poderes', 'Equilíbrio entre Executivo, Legislativo e Judiciário'),
(23, 'Medida cautelar no STF', 'Decisões urgentes do Supremo'),
(24, 'O STF e o Pacto Federativo', 'Conflitos entre União, Estados e Municípios'),
(25, 'Impeachment e o papel do STF', 'A atuação do Supremo no processo'),
(26, 'O STF e tratados internacionais', 'Status dos tratados no ordenamento'),
(27, 'Reclamação constitucional', 'Garantindo o cumprimento das decisões do STF'),
(28, 'O Regimento Interno do STF', 'Regras que organizam o tribunal'),
(29, 'TV Justiça e transparência do STF', 'Transmissão ao vivo dos julgamentos'),
(30, 'O futuro do STF', 'Desafios e perspectivas do tribunal');

-- Senado Federal (30 temas)
INSERT INTO blogger_senado (ordem, titulo, descricao_curta) VALUES
(1, 'O que é o Senado Federal?', 'Função e importância do Senado no Brasil'),
(2, 'Composição do Senado', 'Os 81 senadores e sua distribuição'),
(3, 'Como se elege um senador', 'Sistema eleitoral e mandato de 8 anos'),
(4, 'A Mesa Diretora do Senado', 'Estrutura de direção e seus cargos'),
(5, 'Presidente do Senado', 'Funções e poderes do presidente'),
(6, 'Comissões permanentes do Senado', 'As comissões e suas atribuições'),
(7, 'CPI: Comissão Parlamentar de Inquérito', 'Poder investigativo do Senado'),
(8, 'O processo legislativo no Senado', 'Como nasce uma lei no Senado'),
(9, 'Emendas constitucionais no Senado', 'Como se altera a Constituição'),
(10, 'O Senado e o julgamento de impeachment', 'Papel no processo de impedimento'),
(11, 'Sabatina de autoridades', 'Aprovação de ministros e embaixadores'),
(12, 'O Senado e os tratados internacionais', 'Aprovação de acordos com outros países'),
(13, 'Medidas provisórias no Senado', 'Análise das MPs do presidente'),
(14, 'O papel do Senado na federação', 'Representação dos estados'),
(15, 'Senado e orçamento público', 'Participação na lei orçamentária'),
(16, 'Imunidade parlamentar dos senadores', 'Proteções e prerrogativas'),
(17, 'Conselho de Ética do Senado', 'Disciplina e conduta dos senadores'),
(18, 'Bancadas e blocos partidários', 'Organização política no Senado'),
(19, 'Líderes partidários no Senado', 'Papel das lideranças'),
(20, 'O Diário do Senado Federal', 'Publicação oficial dos trabalhos'),
(21, 'Senado e Câmara: diferenças', 'Comparação entre as duas casas'),
(22, 'Sessões deliberativas do Senado', 'Tipos de sessão e quórum'),
(23, 'Obstrução e filibusterismo', 'Estratégias parlamentares no Senado'),
(24, 'O Senado e a dívida pública', 'Controle do endividamento'),
(25, 'Audiências públicas no Senado', 'Participação popular no legislativo'),
(26, 'A TV Senado', 'Transparência e comunicação'),
(27, 'O Jovem Senador', 'Programa educativo do Senado'),
(28, 'Arquivo e memória do Senado', 'História e patrimônio institucional'),
(29, 'O Senado e os direitos humanos', 'Comissão de Direitos Humanos'),
(30, 'Reformas legislativas importantes', 'Grandes reformas aprovadas pelo Senado');

-- Câmara dos Deputados (30 temas)
INSERT INTO blogger_camara (ordem, titulo, descricao_curta) VALUES
(1, 'O que é a Câmara dos Deputados?', 'Função e importância na democracia brasileira'),
(2, 'Composição da Câmara', 'Os 513 deputados federais'),
(3, 'Como se elege um deputado federal', 'Sistema proporcional e quociente eleitoral'),
(4, 'A Mesa Diretora da Câmara', 'Estrutura de direção e cargos'),
(5, 'Presidente da Câmara', 'Poderes e funções do presidente'),
(6, 'Comissões permanentes da Câmara', 'As comissões e suas atribuições'),
(7, 'CCJ: Comissão de Constituição e Justiça', 'A comissão mais importante'),
(8, 'O processo legislativo na Câmara', 'Da proposta à votação'),
(9, 'Projetos de Lei Ordinária', 'Como funciona a tramitação'),
(10, 'Projetos de Lei Complementar', 'Quando são necessários e como tramitam'),
(11, 'PEC: Proposta de Emenda Constitucional', 'Alterando a Constituição pela Câmara'),
(12, 'Regime de urgência na Câmara', 'Votação acelerada de projetos'),
(13, 'O plenário da Câmara', 'Como funcionam as votações'),
(14, 'Votação nominal x simbólica', 'Tipos de votação no plenário'),
(15, 'Bancadas temáticas na Câmara', 'Ruralistas, evangélicos e outras frentes'),
(16, 'O papel da oposição na Câmara', 'Fiscalização e controle'),
(17, 'CPI na Câmara dos Deputados', 'Investigações parlamentares'),
(18, 'Imunidade parlamentar dos deputados', 'Proteções constitucionais'),
(19, 'Conselho de Ética da Câmara', 'Conduta e disciplina'),
(20, 'Deputados federais x estaduais', 'Diferenças e atribuições'),
(21, 'A Câmara e o orçamento público', 'LOA, LDO e PPA'),
(22, 'Emendas parlamentares', 'Como deputados destinam recursos'),
(23, 'Sessões solenes e homenagens', 'Eventos especiais na Câmara'),
(24, 'O papel do relator de um projeto', 'A importância do parecer'),
(25, 'Câmara e Senado: casa revisora', 'A tramitação bicameral'),
(26, 'Lobby e grupos de pressão', 'Influência na Câmara dos Deputados'),
(27, 'A TV Câmara', 'Transparência e comunicação'),
(28, 'Parlamento Jovem', 'Programa educativo da Câmara'),
(29, 'A Câmara na era digital', 'Votação eletrônica e transparência'),
(30, 'Grandes votações históricas', 'Momentos marcantes da Câmara');

-- Direito Constitucional (30 temas)
INSERT INTO blogger_constitucional (ordem, titulo, descricao_curta) VALUES
(1, 'O que é Direito Constitucional?', 'Conceito e importância do ramo'),
(2, 'A Constituição Federal de 1988', 'A Constituição Cidadã e sua história'),
(3, 'Poder Constituinte Originário', 'A criação de uma nova Constituição'),
(4, 'Poder Constituinte Derivado', 'Emendas e revisão constitucional'),
(5, 'Princípios Fundamentais (Art. 1º a 4º)', 'Soberania, cidadania e dignidade'),
(6, 'Direitos e Garantias Fundamentais', 'O Art. 5º e suas garantias'),
(7, 'Direitos Sociais na Constituição', 'Saúde, educação, trabalho e moradia'),
(8, 'Direitos Políticos', 'Voto, elegibilidade e partidos'),
(9, 'Nacionalidade brasileira', 'Natos e naturalizados'),
(10, 'Organização do Estado', 'União, Estados, DF e Municípios'),
(11, 'Repartição de competências', 'Quem pode legislar sobre o quê'),
(12, 'Separação dos poderes', 'Executivo, Legislativo e Judiciário'),
(13, 'Poder Executivo na Constituição', 'Presidente, governadores e prefeitos'),
(14, 'Poder Legislativo na Constituição', 'Congresso, Assembleias e Câmaras'),
(15, 'Poder Judiciário na Constituição', 'Estrutura e organização'),
(16, 'O Ministério Público', 'Função essencial à justiça'),
(17, 'A Defensoria Pública', 'Acesso à justiça para todos'),
(18, 'Controle de constitucionalidade', 'Difuso e concentrado'),
(19, 'Cláusulas pétreas', 'O que não pode ser mudado'),
(20, 'Estado de Defesa e Estado de Sítio', 'Situações excepcionais'),
(21, 'Intervenção Federal', 'Quando a União intervém nos Estados'),
(22, 'Ordem Econômica na Constituição', 'Livre iniciativa e valorização do trabalho'),
(23, 'Ordem Social na Constituição', 'Seguridade social e educação'),
(24, 'O Sistema Tributário Nacional', 'Tributos na Constituição'),
(25, 'Remédios Constitucionais', 'Habeas corpus, mandado de segurança e outros'),
(26, 'Devido processo legal', 'Ampla defesa e contraditório'),
(27, 'Princípio da igualdade', 'Igualdade formal e material'),
(28, 'Liberdade de expressão', 'Limites e proteção constitucional'),
(29, 'Constituições brasileiras anteriores', 'De 1824 a 1967/69'),
(30, 'Neoconstitucionalismo', 'A nova interpretação constitucional');

-- Tribunais Superiores (30 temas)
INSERT INTO blogger_tribunais (ordem, titulo, descricao_curta) VALUES
(1, 'O que são os Tribunais Superiores?', 'Visão geral do sistema judiciário superior'),
(2, 'STJ: Superior Tribunal de Justiça', 'O tribunal da legislação federal'),
(3, 'Composição do STJ', 'Os 33 ministros e suas turmas'),
(4, 'Competências do STJ', 'O que o STJ pode julgar'),
(5, 'Recurso Especial (REsp)', 'Quando um caso chega ao STJ'),
(6, 'Súmulas do STJ', 'Entendimentos consolidados'),
(7, 'TST: Tribunal Superior do Trabalho', 'Justiça trabalhista no Brasil'),
(8, 'Composição do TST', 'Os 27 ministros trabalhistas'),
(9, 'Competências do TST', 'Recursos e dissídios coletivos'),
(10, 'Recurso de Revista no TST', 'Como um caso trabalhista sobe ao TST'),
(11, 'Súmulas do TST', 'Jurisprudência trabalhista consolidada'),
(12, 'TSE: Tribunal Superior Eleitoral', 'Guardião das eleições brasileiras'),
(13, 'Composição do TSE', 'Os 7 ministros eleitorais'),
(14, 'Competências do TSE', 'Eleições, partidos e candidaturas'),
(15, 'O TSE e as eleições', 'Organização do processo eleitoral'),
(16, 'Propaganda eleitoral e o TSE', 'Regras para campanhas'),
(17, 'STM: Superior Tribunal Militar', 'Justiça militar no Brasil'),
(18, 'Composição do STM', 'Os 15 ministros militares e civis'),
(19, 'Competências do STM', 'Crimes militares e disciplina'),
(20, 'A Justiça Militar da União', 'Estrutura e funcionamento'),
(21, 'Diferença entre STF e STJ', 'Competências distintas dos tribunais'),
(22, 'Como os ministros são escolhidos', 'Processo de nomeação nos tribunais'),
(23, 'Recurso Ordinário nos Tribunais Superiores', 'Tipos e cabimento'),
(24, 'Conflito de competência entre tribunais', 'Quando há dúvida sobre qual tribunal julgar'),
(25, 'Incidente de recursos repetitivos', 'Julgamento de temas em massa'),
(26, 'A informatização dos tribunais', 'Processo eletrônico e PJe'),
(27, 'Turmas e Seções nos Tribunais Superiores', 'Organização interna'),
(28, 'Corregedoria dos Tribunais', 'Fiscalização e disciplina'),
(29, 'O CNJ e os Tribunais Superiores', 'Controle administrativo do Judiciário'),
(30, 'Perspectivas dos Tribunais Superiores', 'Desafios e modernização');
