-- Fase 3: Dropar tabelas vazias/abandonadas
DROP TABLE IF EXISTS "LEIS_COMPLEMENTARES_VADEMECUM";
DROP TABLE IF EXISTS "LEIS_ORDINARIAS_VADEMECUM";
DROP TABLE IF EXISTS "MEDIDAS_PROVISORIAS_VADEMECUM";
DROP TABLE IF EXISTS "PEC_VADEMECUM";
DROP TABLE IF EXISTS "PLP_VADEMECUM";
DROP TABLE IF EXISTS "PL_VADEMECUM";
DROP TABLE IF EXISTS "ENUNCIADOS CNJ";
DROP TABLE IF EXISTS "ENUNCIADOS CNMP";
DROP TABLE IF EXISTS "SUMULAS STM";
DROP TABLE IF EXISTS "SUMULAS TSE";
DROP TABLE IF EXISTS "SUMULAS TST";
DROP TABLE IF EXISTS "SUMULAS TCU";
DROP TABLE IF EXISTS "LEI6015_backup_import";

-- Fase 4: Deduplicar LRF
DELETE FROM "LC 101 - LRF" a USING "LC 101 - LRF" b
WHERE a.id > b.id AND a."Artigo" = b."Artigo";

-- Deduplicar Juizados Cíveis
DELETE FROM "LEI 9099 - JUIZADOS CIVEIS" a USING "LEI 9099 - JUIZADOS CIVEIS" b
WHERE a.id > b.id AND a."Artigo" = b."Artigo";

-- Deduplicar Benefícios
DELETE FROM "LEI 8213 - Benefícios" a USING "LEI 8213 - Benefícios" b
WHERE a.id > b.id AND a."Artigo" = b."Artigo";