-- Criar tabela BIBLIOTECA-POLITICA igual à BIBLIOTECA-CLASSICOS
CREATE TABLE public."BIBLIOTECA-POLITICA" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT, -- usado para orientação: esquerda, centro, direita
  livro TEXT,
  autor TEXT,
  link TEXT,
  imagem TEXT, -- capa salva permanentemente (Google Books ou manual)
  sobre TEXT,
  beneficios TEXT,
  download TEXT,
  "Capa-area" TEXT,
  aula TEXT,
  resumo_capitulos JSONB,
  questoes_resumo JSONB,
  resumo_gerado_em TIMESTAMPTZ,
  capitulos_gerados INTEGER,
  total_capitulos INTEGER
);

-- Habilitar RLS
ALTER TABLE public."BIBLIOTECA-POLITICA" ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública
CREATE POLICY "Permitir leitura pública BIBLIOTECA-POLITICA"
ON public."BIBLIOTECA-POLITICA"
FOR SELECT
USING (true);

-- Política de atualização para service_role (para salvar capas)
CREATE POLICY "Permitir update via service_role BIBLIOTECA-POLITICA"
ON public."BIBLIOTECA-POLITICA"
FOR UPDATE
USING (true)
WITH CHECK (true);

-- Índice para busca por orientação
CREATE INDEX idx_biblioteca_politica_area ON public."BIBLIOTECA-POLITICA" (area);

-- Migrar dados existentes da politica_conteudo_orientacao para a nova tabela
INSERT INTO public."BIBLIOTECA-POLITICA" (area, livro, autor, link, imagem, sobre)
SELECT 
  orientacao as area,
  titulo as livro,
  autor,
  url as link,
  imagem_url as imagem,
  descricao as sobre
FROM public.politica_conteudo_orientacao
WHERE tipo = 'livro'
ORDER BY ordem;