-- Inserir os 29 tópicos de Direito Constitucional (materia_id = 3)
INSERT INTO oab_trilhas_topicos (materia_id, titulo, ordem, status) VALUES
(3, 'Constitucionalismo e Classificação das Constituições', 1, 'pendente'),
(3, 'Poder Constituinte', 2, 'pendente'),
(3, 'Eficácia das Normas Constitucionais', 3, 'pendente'),
(3, 'Espécies de Inconstitucionalidade', 4, 'pendente'),
(3, 'Controle de Constitucionalidade no Brasil', 5, 'pendente'),
(3, 'Controle de Constitucionalidade Difuso', 6, 'pendente'),
(3, 'Controle de Constitucionalidade Concentrado', 7, 'pendente'),
(3, 'Ação Direta de Inconstitucionalidade (ADI): cabimento, competência, legitimidade e efeitos', 8, 'pendente'),
(3, 'ADI Interventiva', 9, 'pendente'),
(3, 'Ação Declaratória de Constitucionalidade (ADC)', 10, 'pendente'),
(3, 'Arguição de Descumprimento de Preceito Fundamental (ADPF)', 11, 'pendente'),
(3, 'Ação Direta de Inconstitucionalidade por Omissão (ADO)', 12, 'pendente'),
(3, 'Súmula Vinculante', 13, 'pendente'),
(3, 'Organização do Estado', 14, 'pendente'),
(3, 'Poder Legislativo', 15, 'pendente'),
(3, 'Comissão Parlamentar de Inquérito (CPI)', 16, 'pendente'),
(3, 'Poder Executivo', 17, 'pendente'),
(3, 'Poder Judiciário', 18, 'pendente'),
(3, 'Ministério Público', 19, 'pendente'),
(3, 'Processo Legislativo', 20, 'pendente'),
(3, 'Funções Essenciais à Justiça', 21, 'pendente'),
(3, 'Defesa do Estado e das Instituições Democráticas', 22, 'pendente'),
(3, 'Direitos e Garantias Fundamentais', 23, 'pendente'),
(3, 'Direitos Sociais', 24, 'pendente'),
(3, 'Nacionalidade', 25, 'pendente'),
(3, 'Direitos Políticos', 26, 'pendente'),
(3, 'Partidos Políticos', 27, 'pendente'),
(3, 'Ordem Social', 28, 'pendente'),
(3, 'Ordem Econômica e Financeira', 29, 'pendente');