-- Tabela para livros contribuídos pelos usuários
CREATE TABLE public."BIBLIOTECA-CONTRIBUICOES" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  livro TEXT NOT NULL,
  autor TEXT,
  idioma TEXT DEFAULT 'pt',
  formato TEXT DEFAULT 'PDF',
  tamanho TEXT,
  imagem TEXT,
  sobre TEXT,
  download TEXT,
  md5 TEXT UNIQUE,
  contribuidor_id UUID REFERENCES auth.users(id),
  aprovado BOOLEAN DEFAULT false,
  area TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Índices para performance
CREATE INDEX idx_contribuicoes_md5 ON public."BIBLIOTECA-CONTRIBUICOES" (md5);
CREATE INDEX idx_contribuicoes_aprovado ON public."BIBLIOTECA-CONTRIBUICOES" (aprovado);
CREATE INDEX idx_contribuicoes_area ON public."BIBLIOTECA-CONTRIBUICOES" (area);

-- Enable RLS
ALTER TABLE public."BIBLIOTECA-CONTRIBUICOES" ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
-- Todos podem ver livros aprovados
CREATE POLICY "Livros aprovados são públicos"
ON public."BIBLIOTECA-CONTRIBUICOES"
FOR SELECT
USING (aprovado = true);

-- Usuários autenticados podem ver seus próprios livros (mesmo não aprovados)
CREATE POLICY "Usuários veem próprias contribuições"
ON public."BIBLIOTECA-CONTRIBUICOES"
FOR SELECT
USING (auth.uid() = contribuidor_id);

-- Usuários autenticados podem inserir
CREATE POLICY "Usuários podem contribuir livros"
ON public."BIBLIOTECA-CONTRIBUICOES"
FOR INSERT
WITH CHECK (auth.uid() = contribuidor_id);

-- Usuários podem atualizar próprias contribuições
CREATE POLICY "Usuários podem editar próprias contribuições"
ON public."BIBLIOTECA-CONTRIBUICOES"
FOR UPDATE
USING (auth.uid() = contribuidor_id);

-- Trigger para updated_at
CREATE TRIGGER update_contribuicoes_updated_at
BEFORE UPDATE ON public."BIBLIOTECA-CONTRIBUICOES"
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();